// Market temalı ikon kütüphanesi (lucide-react, açık kaynak).
// Banner'larda ve admin ikon seçicide kullanılır. Anahtar = DB'de saklanan
// stabil ad (banners.icon); değer = lucide bileşeni.
// Yeni ikon eklemek için: lucide'den import et + BANNER_ICONS'a ekle.

import {
  Apple,
  Carrot,
  Beef,
  Milk,
  Croissant,
  CupSoda,
  Coffee,
  IceCreamCone,
  Cookie,
  Candy,
  Nut,
  Wheat,
  Soup,
  Fish,
  Egg,
  Drumstick,
  Ham,
  Salad,
  Pizza,
  Sandwich,
  Banana,
  Cherry,
  Grape,
  Citrus,
  Popcorn,
  Beer,
  Wine,
  Droplets,
  Snowflake,
  Flame,
  FlameKindling,
  Baby,
  PawPrint,
  Cigarette,
  SprayCan,
  ScrollText,
  Sparkles,
  Pill,
  Utensils,
  Umbrella,
  Sun,
  LifeBuoy,
  Bug,
  BatteryCharging,
  ShoppingBasket,
  ShoppingCart,
  Gift,
  BadgePercent,
  Percent,
  Truck,
  Bike,
  Store,
  Tag,
  Ticket,
  Leaf,
  Sprout,
  Wallet,
  CreditCard,
  Banknote,
  Clock,
  Calendar,
  Heart,
  Star,
  ThumbsUp,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** DB anahtarı → lucide bileşeni. 50+ market temalı ikon. */
export const BANNER_ICONS: Record<string, LucideIcon> = {
  "shopping-basket": ShoppingBasket,
  "shopping-cart": ShoppingCart,
  store: Store,
  gift: Gift,
  "badge-percent": BadgePercent,
  percent: Percent,
  tag: Tag,
  ticket: Ticket,
  truck: Truck,
  bike: Bike,
  clock: Clock,
  calendar: Calendar,
  wallet: Wallet,
  "credit-card": CreditCard,
  banknote: Banknote,
  sparkles: Sparkles,
  heart: Heart,
  star: Star,
  "thumbs-up": ThumbsUp,
  zap: Zap,
  leaf: Leaf,
  sprout: Sprout,
  apple: Apple,
  carrot: Carrot,
  banana: Banana,
  cherry: Cherry,
  grape: Grape,
  citrus: Citrus,
  salad: Salad,
  beef: Beef,
  ham: Ham,
  drumstick: Drumstick,
  fish: Fish,
  egg: Egg,
  milk: Milk,
  croissant: Croissant,
  wheat: Wheat,
  soup: Soup,
  pizza: Pizza,
  sandwich: Sandwich,
  "cup-soda": CupSoda,
  coffee: Coffee,
  beer: Beer,
  wine: Wine,
  "ice-cream-cone": IceCreamCone,
  cookie: Cookie,
  candy: Candy,
  nut: Nut,
  popcorn: Popcorn,
  droplets: Droplets,
  snowflake: Snowflake,
  flame: Flame,
  "flame-kindling": FlameKindling,
  utensils: Utensils,
  "scroll-text": ScrollText,
  "spray-can": SprayCan,
  pill: Pill,
  baby: Baby,
  "paw-print": PawPrint,
  cigarette: Cigarette,
  umbrella: Umbrella,
  sun: Sun,
  "life-buoy": LifeBuoy,
  bug: Bug,
  "battery-charging": BatteryCharging,
};

/** Admin seçici için sıralı liste (etiket = okunur Türkçe ad). */
export const BANNER_ICON_OPTIONS: { key: string; label: string }[] = [
  { key: "badge-percent", label: "İndirim rozeti" },
  { key: "percent", label: "Yüzde" },
  { key: "tag", label: "Etiket" },
  { key: "ticket", label: "Kupon / bilet" },
  { key: "gift", label: "Hediye" },
  { key: "truck", label: "Kamyon (teslimat)" },
  { key: "bike", label: "Motor (kurye)" },
  { key: "clock", label: "Saat / hız" },
  { key: "calendar", label: "Takvim" },
  { key: "wallet", label: "Cüzdan" },
  { key: "credit-card", label: "Kredi kartı" },
  { key: "banknote", label: "Nakit" },
  { key: "sparkles", label: "Parıltı" },
  { key: "star", label: "Yıldız" },
  { key: "heart", label: "Kalp" },
  { key: "thumbs-up", label: "Beğeni" },
  { key: "zap", label: "Şimşek" },
  { key: "shopping-basket", label: "Sepet" },
  { key: "shopping-cart", label: "Alışveriş arabası" },
  { key: "store", label: "Market" },
  { key: "leaf", label: "Yaprak (taze)" },
  { key: "sprout", label: "Filiz (organik)" },
  { key: "apple", label: "Elma" },
  { key: "carrot", label: "Havuç" },
  { key: "banana", label: "Muz" },
  { key: "cherry", label: "Kiraz" },
  { key: "grape", label: "Üzüm" },
  { key: "citrus", label: "Narenciye" },
  { key: "salad", label: "Salata" },
  { key: "beef", label: "Et" },
  { key: "ham", label: "Şarküteri" },
  { key: "drumstick", label: "Tavuk" },
  { key: "fish", label: "Balık" },
  { key: "egg", label: "Yumurta" },
  { key: "milk", label: "Süt" },
  { key: "croissant", label: "Fırın" },
  { key: "wheat", label: "Bakliyat" },
  { key: "soup", label: "Çorba / hazır" },
  { key: "pizza", label: "Pizza" },
  { key: "sandwich", label: "Sandviç" },
  { key: "cup-soda", label: "İçecek" },
  { key: "coffee", label: "Kahve / çay" },
  { key: "beer", label: "Bira" },
  { key: "wine", label: "Şarap" },
  { key: "ice-cream-cone", label: "Dondurma" },
  { key: "cookie", label: "Bisküvi" },
  { key: "candy", label: "Şekerleme" },
  { key: "nut", label: "Kuruyemiş" },
  { key: "popcorn", label: "Cips / mısır" },
  { key: "droplets", label: "Su / sıvı" },
  { key: "snowflake", label: "Donuk / dondurma" },
  { key: "flame", label: "Mangal / ateş" },
  { key: "flame-kindling", label: "Çakmak / tüp" },
  { key: "utensils", label: "Piknik / çatal" },
  { key: "scroll-text", label: "Kağıt ürünleri" },
  { key: "spray-can", label: "Temizlik" },
  { key: "pill", label: "Vitamin / ilaç" },
  { key: "baby", label: "Bebek" },
  { key: "paw-print", label: "Evcil hayvan" },
  { key: "umbrella", label: "Plaj / şemsiye" },
  { key: "sun", label: "Güneş / yaz" },
  { key: "life-buoy", label: "Şişme / havuz" },
  { key: "bug", label: "Böcek kovucu" },
  { key: "battery-charging", label: "Şarj / pil" },
];

/**
 * Banner ikonunu çöz: önce açık seçilen icon (banners.icon), yoksa başlık
 * içeriğine göre otomatik tahmin, o da yoksa varsayılan sparkles.
 */
export function resolveBannerIcon(icon: string, title: string): LucideIcon {
  if (icon && BANNER_ICONS[icon]) return BANNER_ICONS[icon];
  const t = title.toLocaleLowerCase("tr");
  if (/indirim|%|yüzde|fırsat|kampanya/.test(t)) return BadgePercent;
  if (/teslimat|kargo|dakika|kapında|kurye/.test(t)) return Truck;
  if (/hediye|hoşgeldin|hoş geldin|ilk sipariş/.test(t)) return Gift;
  if (/kahvalt|süt|peynir/.test(t)) return Milk;
  if (/meyve|sebze|manav|taze/.test(t)) return Carrot;
  if (/mangal|kömür/.test(t)) return Flame;
  if (/atıştır|cips|çerez/.test(t)) return Cookie;
  if (/temizlik|deterjan/.test(t)) return SprayCan;
  if (/kahve|çay/.test(t)) return Coffee;
  if (/kapıda|ödeme|nakit|kart/.test(t)) return Wallet;
  return Sparkles;
}
