-- ============================================================
-- Yeni Mahalle Market: Getir seviyesinde katalog genisletmesi (B).
-- 26 kategoriye kategori basina 10-20 yeni, gercekci urun eklenir
-- (toplam 442 urun). Mevcut urunlerle ad/marka/boyut olarak
-- cakismayan yeni SKU'lar secildi; subcategories.ts icindeki
-- catch-all kurallari sayesinde her urun otomatik olarak dogru
-- alt kategoriye duser (subcategories.ts'e DOKUNULMADI).
--
-- Kolon sirasi mevcut seed ile BIREBIR AYNI:
--   (category_slug, name, slug, brand, size_text, description,
--    price, compare_at_price, unit, is_featured, sort)
-- compare_at_price HER ZAMAN null (indirim yok).
-- Sort degerleri 6000'den baslar (mevcut max deger 4044'tu,
-- bu yuzden cakisma yok). Slug'lar ASCII ve benzersiz; mevcut
-- katalogdaki ~2140 slug'a karsi ve dosya ici olarak dogrulandi.
-- Idempotent: on conflict (slug) do nothing.
-- ============================================================

insert into public.products (category_slug, name, slug, brand, size_text, description, price, compare_at_price, unit, is_featured, sort) values
  -- sarkuteri-et (20 yeni urun)
  ('sarkuteri-et', 'Beypiliç Tavuk Şinitzel', 'beypilic-tavuk-sinitzel-500-g', 'Beypiliç', '500 g', 'Kızartmaya hazır, galeta unlu tavuk göğsü şinitzel.', 129.90, null, 'adet', false, 6000),
  ('sarkuteri-et', 'Erpiliç Tavuk Pirzola', 'erpilic-tavuk-pirzola-1-kg', 'Erpiliç', '1 kg', 'Izgara ve fırına uygun, kemikli tavuk pirzola.', 149.90, null, 'kg', false, 6001),
  ('sarkuteri-et', 'Şenpiliç Hindi Kıyma', 'senpilic-hindi-kiyma-500-g', 'Şenpiliç', '500 g', 'Az yağlı, köfte ve börek harcına uygun hindi kıyma.', 159.90, null, 'adet', false, 6002),
  ('sarkuteri-et', 'Namet Piliç Jambon', 'namet-pilic-jambon-150-g', 'Namet', '150 g', 'İnce dilimli, kahvaltılık piliç göğsü jambon.', 89.90, null, 'adet', false, 6003),
  ('sarkuteri-et', 'Maret Frankfurter Sosis', 'maret-frankfurter-sosis-300-g', 'Maret', '300 g', 'Klasik lezzette, haşlamaya hazır dana frankfurter sosis.', 119.90, null, 'adet', false, 6004),
  ('sarkuteri-et', 'Pınar Tavuk Burger Köftesi', 'pinar-tavuk-burger-koftesi-300-g', 'Pınar', '300 g', 'Izgara ve tavada pişirmeye hazır tavuk burger köftesi.', 139.90, null, 'adet', false, 6005),
  ('sarkuteri-et', 'Aytaç Tavuk Döner Dilim', 'aytac-tavuk-doner-dilim-500-g', 'Aytaç', '500 g', 'Baharatlı marine edilmiş, tavada çevrilen dilim tavuk döner.', 179.90, null, 'adet', false, 6006),
  ('sarkuteri-et', 'Polonez Dana Salam Dilimli', 'polonez-dana-salam-dilimli-150-g', 'Polonez', '150 g', 'İnce dilim kesilmiş, kahvaltılık dana salam.', 99.90, null, 'adet', false, 6007),
  ('sarkuteri-et', 'Apikoğlu Kayseri Pastırma Dilim', 'apikoglu-kayseri-pastirma-dilim-100-g', 'Apikoğlu', '100 g', 'Çemenli, ince dilimlenmiş geleneksel Kayseri pastırması.', 189.90, null, 'adet', true, 6008),
  ('sarkuteri-et', 'Gedik Kayseri Sucuk', 'gedik-kayseri-sucuk-400-g', 'Gedik', '400 g', 'Baharatlı, geleneksel tarifle üretilen Kayseri usulü sucuk.', 219.90, null, 'adet', false, 6009),
  ('sarkuteri-et', 'Dana Pirzola', 'dana-pirzola-1-kg', '', '1 kg', 'Kemikli, ızgaralık taze dana pirzola.', 449.90, null, 'kg', true, 6010),
  ('sarkuteri-et', 'Dana Böbrek', 'dana-bobrek-500-g', '', '500 g', 'Temizlenmiş, ızgaralık taze dana böbrek.', 199.90, null, 'adet', false, 6011),
  ('sarkuteri-et', 'Dana İşkembe', 'dana-iskembe-1-kg', '', '1 kg', 'Temizlenmiş, çorbalık taze dana işkembe.', 249.90, null, 'kg', false, 6012),
  ('sarkuteri-et', 'Kuzu Tandır Kavurma', 'kuzu-tandir-kavurma-500-g', '', '500 g', 'Yavaş pişmiş, servise hazır kuzu tandır kavurma.', 349.90, null, 'adet', false, 6013),
  ('sarkuteri-et', 'Kuzu Şiş Kuşbaşı', 'kuzu-sis-kusbasi-500-g', '', '500 g', 'Marine edilmiş, şişe dizmeye hazır kuzu kuşbaşı.', 389.90, null, 'adet', false, 6014),
  ('sarkuteri-et', 'Tavuk Şiş Kuşbaşı', 'tavuk-sis-kusbasi-500-g', '', '500 g', 'Baharatlı marine edilmiş, şişlik tavuk göğsü kuşbaşı.', 149.90, null, 'adet', false, 6015),
  ('sarkuteri-et', 'Dana But Kuşbaşı', 'dana-but-kusbasi-500-g', '', '500 g', 'Yahni ve güveç için taze dana but kuşbaşı.', 329.90, null, 'adet', false, 6016),
  ('sarkuteri-et', 'Hindi Şinitzel', 'hindi-sinitzel-500-g', '', '500 g', 'İnce dilimlenmiş, kızartmaya hazır hindi göğsü şinitzel.', 169.90, null, 'adet', false, 6017),
  ('sarkuteri-et', 'Namet Dana Bacon Küp', 'namet-dana-bacon-kup-100-g', 'Namet', '100 g', 'Salata ve makarna için küp kesim dana bacon.', 79.90, null, 'adet', false, 6018),
  ('sarkuteri-et', 'Kuzu Kokoreç', 'kuzu-kokorec-500-g', '', '500 g', 'Temizlenmiş, ızgaraya hazır geleneksel kuzu kokoreç.', 279.90, null, 'adet', false, 6019),
  -- ekmek-firin (18 yeni urun)
  ('ekmek-firin', 'Uno Ekşi Mayalı Ekmek', 'uno-eksi-mayali-ekmek-400-g', 'Uno', '400 g', 'Doğal ekşi mayayla üretilen, çıtır kabuklu ekmek.', 44.90, null, 'adet', false, 6020),
  ('ekmek-firin', 'Uno Çokgen Tost Ekmeği', 'uno-cokgen-tost-ekmegi-550-g', 'Uno', '550 g', 'Kalın dilimli, tost makinesine uygun çokgen ekmek.', 69.90, null, 'adet', false, 6021),
  ('ekmek-firin', 'Eriş Kaşarlı Poğaça', 'eris-kasarli-pogaca-4lu', 'Eriş', '4''lü', 'İçi bol kaşarlı, taze pişmiş poğaça paketi.', 64.90, null, 'paket', false, 6022),
  ('ekmek-firin', 'Eriş Sade Poğaça', 'eris-sade-pogaca-6li', 'Eriş', '6''lı', 'Tereyağlı hamurdan yapılan, günlük sade poğaça.', 59.90, null, 'paket', false, 6023),
  ('ekmek-firin', 'Sinangil Simit', 'sinangil-simit-5li', 'Sinangil', '5''li', 'Susamlı, fırın taze klasik simit paketi.', 54.90, null, 'paket', false, 6024),
  ('ekmek-firin', 'Tam Buğday Lavaş', 'tam-bugday-lavas-5li', '', '5''li', 'İnce açılmış, dürüm ve wrap için tam buğday lavaş.', 39.90, null, 'paket', false, 6025),
  ('ekmek-firin', 'Mısır Ekmeği', 'misir-ekmegi-400-g', '', '400 g', 'Mısır unu katkılı, hafif tatlımsı köy usulü ekmek.', 44.90, null, 'adet', false, 6026),
  ('ekmek-firin', 'Susamlı Çubuk Kraker Ekmeği', 'susamli-cubuk-kraker-ekmegi-150-g', '', '150 g', 'Çıtır dokulu, susamlı ince çubuk ekmek.', 34.90, null, 'adet', false, 6027),
  ('ekmek-firin', 'Katmer Hamuru', 'katmer-hamuru-400-g', '', '400 g', 'Çok katlı, tepside pişirmeye hazır katmer hamuru.', 79.90, null, 'adet', false, 6028),
  ('ekmek-firin', 'Su Böreği Yufkası', 'su-boregi-yufkasi-500-g', '', '500 g', 'İnce açılmış, ıslatılmaya hazır su böreği yufkası.', 49.90, null, 'adet', false, 6029),
  ('ekmek-firin', 'Pizza Hamuru Kabartılmış', 'pizza-hamuru-kabartilmis-300-g', '', '300 g', 'Elle açılmaya hazır, mayalanmış pizza hamuru.', 39.90, null, 'adet', false, 6030),
  ('ekmek-firin', 'Sarımsaklı Baget Ekmek', 'sarimsakli-baget-ekmek-300-g', '', '300 g', 'Fırınlanmaya hazır, tereyağlı sarımsaklı baget ekmek.', 54.90, null, 'adet', false, 6031),
  ('ekmek-firin', 'Zencefilli Kurabiye', 'zencefilli-kurabiye-200-g', '', '200 g', 'Baharatlı, çıtır dokulu zencefilli kurabiye paketi.', 64.90, null, 'adet', false, 6032),
  ('ekmek-firin', 'Tahinli Kurabiye', 'tahinli-kurabiye-200-g', '', '200 g', 'Geleneksel tarifle pişirilen tahinli un kurabiyesi.', 59.90, null, 'adet', false, 6033),
  ('ekmek-firin', 'Cevizli Çörek', 'cevizli-corek-4lu', '', '4''lü', 'İçi bol cevizli, taze pişmiş çörek paketi.', 74.90, null, 'paket', false, 6034),
  ('ekmek-firin', 'Yulaflı Ekmek', 'yulafli-ekmek-400-g', '', '400 g', 'Yulaf ezmesi katkılı, lifli günlük ekmek.', 49.90, null, 'adet', false, 6035),
  ('ekmek-firin', 'Kepekli Simit', 'kepekli-simit-adet', '', '1 adet', 'Kepek unuyla üretilen, daha lifli simit.', 19.90, null, 'adet', false, 6036),
  ('ekmek-firin', 'Antep Peynirli Açma', 'antep-peynirli-acma-adet', '', '1 adet', 'İçi bol peynirli, yumuşak dokulu açma.', 34.90, null, 'adet', false, 6037),
  -- bakliyat-makarna (18 yeni urun)
  ('bakliyat-makarna', 'Baktat Yeşil Mercimek', 'baktat-yesil-mercimek-1-kg', 'Baktat', '1 kg', 'Ayıklanmış, çorbalık ve yemeklik yeşil mercimek.', 89.90, null, 'adet', false, 6038),
  ('bakliyat-makarna', 'Baktat Nohut', 'baktat-nohut-1-kg', 'Baktat', '1 kg', 'İri taneli, haşlamaya hazır kuru nohut.', 84.90, null, 'adet', false, 6039),
  ('bakliyat-makarna', 'Mutlu Kuru Fasulye', 'mutlu-kuru-fasulye-1-kg', 'Mutlu', '1 kg', 'Dermason cinsi, iri taneli kuru fasulye.', 99.90, null, 'adet', false, 6040),
  ('bakliyat-makarna', 'Söke Pilavlık Bulgur', 'soke-pilavlik-bulgur-2-5-kg', 'Söke', '2,5 kg', 'İri çekim, pilavlık ekonomik boy bulgur.', 199.90, null, 'adet', false, 6041),
  ('bakliyat-makarna', 'Barilla Fusilli', 'barilla-fusilli-500-g', 'Barilla', '500 g', 'Burgu formunda, İtalyan usulü durum buğdayı makarna.', 84.90, null, 'adet', false, 6042),
  ('bakliyat-makarna', 'Barilla Lazanya Levha', 'barilla-lazanya-levha-500-g', 'Barilla', '500 g', 'Fırınlık lazanya için hazır durum buğdayı levha.', 119.90, null, 'adet', false, 6043),
  ('bakliyat-makarna', 'Filiz Şehriye', 'filiz-sehriye-500-g', 'Filiz', '500 g', 'İnce kesim, çorbalık ve pilavlık şehriye.', 39.90, null, 'adet', false, 6044),
  ('bakliyat-makarna', 'Piyale Boncuk Makarna', 'piyale-boncuk-makarna-500-g', 'Piyale', '500 g', 'Çocuklar için minik boncuk formunda makarna.', 44.90, null, 'adet', false, 6045),
  ('bakliyat-makarna', 'Reis Nohut', 'reis-nohut-2-5-kg', 'Reis', '2,5 kg', 'Ekonomik boy, iri taneli kuru nohut.', 199.90, null, 'adet', false, 6046),
  ('bakliyat-makarna', 'Duru Kırmızı Mercimek', 'duru-kirmizi-mercimek-2-5-kg', 'Duru', '2,5 kg', 'Ekonomik boy, çorbalık kırmızı mercimek.', 224.90, null, 'adet', false, 6047),
  ('bakliyat-makarna', 'Yayla Barbunya Fasulyesi', 'yayla-barbunya-fasulyesi-1-kg', 'Yayla', '1 kg', 'Benekli, yemeklik kuru barbunya fasulyesi.', 94.90, null, 'adet', false, 6048),
  ('bakliyat-makarna', 'Nuh Tam Buğday Makarna', 'nuh-tam-bugday-makarna-500-g', 'Nuh', '500 g', 'Lifli beslenme için tam buğday unundan makarna.', 54.90, null, 'adet', false, 6049),
  ('bakliyat-makarna', 'Kestane Kabuğu Fasulye', 'kestane-kabugu-fasulye-500-g', '', '500 g', 'Benekli kabuklu, yemeklik özel kestane fasulyesi.', 69.90, null, 'adet', false, 6050),
  ('bakliyat-makarna', 'Yeşil Bezelye Kuru', 'yesil-bezelye-kuru-500-g', '', '500 g', 'Haşlamaya hazır, kuru yeşil bezelye.', 54.90, null, 'adet', false, 6051),
  ('bakliyat-makarna', 'Aşurelik Karışık Bakliyat', 'asurelik-karisik-bakliyat-500-g', '', '500 g', 'Aşure tarifi için hazır karışık tahıl ve bakliyat.', 64.90, null, 'adet', false, 6052),
  ('bakliyat-makarna', 'Kırmızı Kinoa', 'kirmizi-kinoa-400-g', '', '400 g', 'Glutensiz, protein değeri yüksek kırmızı kinoa.', 149.90, null, 'adet', false, 6053),
  ('bakliyat-makarna', 'Tam Buğday Kuskus', 'tam-bugday-kuskus-500-g', '', '500 g', 'Lifli beslenme için tam buğday unundan kuskus.', 59.90, null, 'adet', false, 6054),
  ('bakliyat-makarna', 'İnce Köftelik Bulgur', 'ince-koftelik-bulgur-2-5-kg', '', '2,5 kg', 'Çiğ köfte ve içli köfte için ince çekim bulgur.', 189.90, null, 'adet', false, 6055),
  -- konserve-hazir-yemek (18 yeni urun)
  ('konserve-hazir-yemek', 'Tat Nohut Konserve', 'tat-nohut-konserve-800-g', 'Tat', '800 g', 'Haşlanmış, salata ve yemeklere hazır nohut konservesi.', 74.90, null, 'adet', false, 6056),
  ('konserve-hazir-yemek', 'Tamek Mısır Konserve', 'tamek-misir-konserve-300-g', 'Tamek', '300 g', 'Salatalık, tatlı sarı mısır tane konservesi.', 49.90, null, 'adet', false, 6057),
  ('konserve-hazir-yemek', 'Tukaş Zeytinyağlı Barbunya', 'tukas-zeytinyagli-barbunya-800-g', 'Tukaş', '800 g', 'Servise hazır, zeytinyağlı barbunya pilaki konservesi.', 89.90, null, 'adet', false, 6058),
  ('konserve-hazir-yemek', 'Dardanel Somon Konserve', 'dardanel-somon-konserve-160-g', 'Dardanel', '160 g', 'Salata ve sandviçlik, kemiksiz somon konservesi.', 129.90, null, 'adet', false, 6059),
  ('konserve-hazir-yemek', 'Beşler Bezelye Konserve', 'besler-bezelye-konserve-800-g', 'Beşler', '800 g', 'Garnitürlük, süzme bezelye konservesi.', 69.90, null, 'adet', false, 6060),
  ('konserve-hazir-yemek', 'Knorr Şehriye Çorbası', 'knorr-sehriye-corbasi-65-g', 'Knorr', '65 g', 'Pratik hazırlanan, tavuklu şehriye çorbası.', 34.90, null, 'adet', false, 6061),
  ('konserve-hazir-yemek', 'Continental Mantar Çorbası', 'continental-mantar-corbasi-61-g', 'Continental', '61 g', 'Kremalı dokulu, hazır mantar çorbası.', 39.90, null, 'adet', false, 6062),
  ('konserve-hazir-yemek', 'Tat Kırmızı Fasulye Konserve', 'tat-kirmizi-fasulye-konserve-800-g', 'Tat', '800 g', 'Haşlanmış, yemeklik kırmızı fasulye konservesi.', 79.90, null, 'adet', false, 6063),
  ('konserve-hazir-yemek', 'Sur Yıldızı Domates Salçası', 'sur-yildizi-domates-salcasi-830-g', 'Sur Yıldızı', '830 g', 'Koyu kıvamlı, katkısız domates salçası.', 129.90, null, 'adet', false, 6064),
  ('konserve-hazir-yemek', 'Tamek Nar Ekşili Salata Sosu', 'tamek-nar-eksili-salata-sosu-300-g', 'Tamek', '300 g', 'Ekşi-tatlı dengeli, hazır nar ekşili salata sosu.', 59.90, null, 'adet', false, 6065),
  ('konserve-hazir-yemek', 'Hazır Karnıyarık Konserve', 'hazir-karniyarik-konserve-400-g', '', '400 g', 'Isıtılıp servis edilen, kıymalı patlıcan karnıyarık.', 89.90, null, 'adet', false, 6066),
  ('konserve-hazir-yemek', 'Hazır Türlü Konserve', 'hazir-turlu-konserve-400-g', '', '400 g', 'Karışık sebzeli, doğal pişmiş türlü yemeği.', 79.90, null, 'adet', false, 6067),
  ('konserve-hazir-yemek', 'İmam Bayıldı Hazır', 'imam-bayildi-hazir-400-g', '', '400 g', 'Zeytinyağlı, servise hazır imam bayıldı.', 84.90, null, 'adet', false, 6068),
  ('konserve-hazir-yemek', 'Mantarlı Tavuk Sote Hazır', 'mantarli-tavuk-sote-hazir-400-g', '', '400 g', 'Kremalı sos içinde, ısıtılmaya hazır tavuk sote.', 109.90, null, 'adet', false, 6069),
  ('konserve-hazir-yemek', 'Kremalı Ispanak Hazır', 'kremali-ispanak-hazir-400-g', '', '400 g', 'Kremalı sosla hazırlanmış, servise hazır ıspanak.', 74.90, null, 'adet', false, 6070),
  ('konserve-hazir-yemek', 'Nohutlu Pilav Hazır', 'nohutlu-pilav-hazir-400-g', '', '400 g', 'Etli nohutlu, ısıtılıp servis edilen pilav.', 89.90, null, 'adet', false, 6071),
  ('konserve-hazir-yemek', 'Ton Balıklı Salata Konserve', 'ton-balikli-salata-konserve-185-g', '', '185 g', 'Sebzeli, açılıp yenmeye hazır ton balıklı salata.', 69.90, null, 'adet', false, 6072),
  ('konserve-hazir-yemek', 'Acılı Ezme Konserve', 'acili-ezme-konserve-300-g', '', '300 g', 'Domates ve biberli, mezelik acılı ezme konservesi.', 54.90, null, 'adet', false, 6073),
  -- yag-sos-baharat (18 yeni urun)
  ('yag-sos-baharat', 'Komili Zeytinyağı Erken Hasat', 'komili-zeytinyagi-erken-hasat-1-l', 'Komili', '1 L', 'Soğuk sıkım, erken hasat naturel sızma zeytinyağı.', 349.90, null, 'adet', true, 6074),
  ('yag-sos-baharat', 'Kırlangıç Ayçiçek Yağı', 'kirlangic-aycicek-yagi-5-l', 'Kırlangıç', '5 L', 'Ailelik boy, günlük kullanıma uygun ayçiçek yağı.', 449.90, null, 'adet', false, 6075),
  ('yag-sos-baharat', 'Orkide Mısırözü Yağı', 'orkide-misirozu-yagi-2-l', 'Orkide', '2 L', 'Kızartma ve yemekler için mısırözü yağı.', 199.90, null, 'adet', false, 6076),
  ('yag-sos-baharat', 'Yudum Kanola Yağı', 'yudum-kanola-yagi-4-l', 'Yudum', '4 L', 'Doymuş yağ oranı düşük, hafif kanola yağı.', 329.90, null, 'adet', false, 6077),
  ('yag-sos-baharat', 'Tariş Sızma Zeytinyağı', 'taris-sizma-zeytinyagi-500-ml', 'Tariş', '500 ml', 'Ege zeytininden soğuk sıkım naturel sızma zeytinyağı.', 219.90, null, 'adet', false, 6078),
  ('yag-sos-baharat', 'Heinz Ketçap Acı', 'heinz-ketcap-aci-500-g', 'Heinz', '500 g', 'Acı biberli, yoğun kıvamlı domates ketçabı.', 89.90, null, 'adet', false, 6079),
  ('yag-sos-baharat', 'Calve Mayonez', 'calve-mayonez-400-g', 'Calve', '400 g', 'Kremamsı dokulu, klasik tarif mayonez.', 84.90, null, 'adet', false, 6080),
  ('yag-sos-baharat', 'Develi Kırmızı Toz Biber', 'develi-kirmizi-toz-biber-200-g', 'Develi', '200 g', 'Gaziantep usulü, tatlı kırmızı toz biber.', 89.90, null, 'adet', false, 6081),
  ('yag-sos-baharat', 'Kükre Kimyon', 'kukre-kimyon-150-g', 'Kükre', '150 g', 'Köfte ve kavurmalarda kullanılan öğütülmüş kimyon.', 54.90, null, 'adet', false, 6082),
  ('yag-sos-baharat', 'Kükre Karabiber', 'kukre-karabiber-150-g', 'Kükre', '150 g', 'Taze öğütülmüş, aromatik karabiber.', 64.90, null, 'adet', false, 6083),
  ('yag-sos-baharat', 'Değirmen Tuz İyotlu', 'degirmen-tuz-iyotlu-750-g', 'Değirmen', '750 g', 'İnce taneli, iyotlu sofra tuzu.', 24.90, null, 'adet', false, 6084),
  ('yag-sos-baharat', 'Tat Barbekü Sos', 'tat-barbeku-sos-350-g', 'Tat', '350 g', 'Dumanlı aromalı, ızgaralık barbekü sosu.', 69.90, null, 'adet', false, 6085),
  ('yag-sos-baharat', 'Nar Ekşisi Ev Yapımı', 'nar-eksisi-ev-yapimi-400-ml', '', '400 ml', 'Koyu kıvamlı, katkısız ev yapımı nar ekşisi.', 119.90, null, 'adet', false, 6086),
  ('yag-sos-baharat', 'Elma Sirkesi Doğal', 'elma-sirkesi-dogal-500-ml', '', '500 ml', 'Filtrelenmemiş, anasıyla doğal elma sirkesi.', 79.90, null, 'adet', false, 6087),
  ('yag-sos-baharat', 'Zencefil Toz Baharat', 'zencefil-toz-baharat-100-g', '', '100 g', 'Tatlı ve tuzlu tariflerde kullanılan toz zencefil.', 49.90, null, 'adet', false, 6088),
  ('yag-sos-baharat', 'Sumak Baharat', 'sumak-baharat-100-g', '', '100 g', 'Ekşimsi aromalı, salata ve kebaplık sumak.', 44.90, null, 'adet', false, 6089),
  ('yag-sos-baharat', 'Pul Biber Antep', 'pul-biber-antep-200-g', '', '200 g', 'Yağlı, orta acı Gaziantep usulü pul biber.', 79.90, null, 'adet', false, 6090),
  ('yag-sos-baharat', 'Toz Şeker Kilo', 'toz-seker-kilo-1-kg', '', '1 kg', 'İnce kristalli, günlük kullanım toz şeker.', 44.90, null, 'adet', false, 6091),
  -- atistirmalik (20 yeni urun)
  ('atistirmalik', 'Ülker Çokokrem Sandviç Bisküvi', 'ulker-cokokrem-sandvic-biskuvi-8li', 'Ülker', '8''li', 'Kakaolu kremalı, iki kat bisküvili sandviç atıştırmalık.', 54.90, null, 'paket', false, 6092),
  ('atistirmalik', 'Ülker Halley Mini', 'ulker-halley-mini-12li', 'Ülker', '12''li', 'Marshmallow dolgulu, mini boy çikolata kaplı bisküvi.', 64.90, null, 'paket', false, 6093),
  ('atistirmalik', 'Ülker Karam Fıstıklı Gofret', 'ulker-karam-fistikli-gofret-4lu', 'Ülker', '4''lü', 'Fıstık kremalı katları çikolatayla kaplı gofret.', 49.90, null, 'paket', false, 6094),
  ('atistirmalik', 'Ülker Rondo Kakaolu', 'ulker-rondo-kakaolu-8li', 'Ülker', '8''li', 'Kakaolu kremalı, klasik yuvarlak sandviç bisküvi.', 59.90, null, 'paket', false, 6095),
  ('atistirmalik', 'Torku Baton Kek Kakaolu', 'torku-baton-kek-kakaolu-adet', 'Torku', '55 g', 'Yumuşak dokulu, kakaolu tekli baton kek.', 14.90, null, 'adet', false, 6096),
  ('atistirmalik', 'Torku Fındıklı Gofret', 'torku-findikli-gofret-4lu', 'Torku', '4''lü', 'Fındık kremalı katları çikolatayla kaplı gofret.', 44.90, null, 'paket', false, 6097),
  ('atistirmalik', 'Torku Tam Buğday Bisküvi', 'torku-tam-bugday-biskuvi-200-g', 'Torku', '200 g', 'Lifli beslenme için tam buğday unlu bisküvi.', 34.90, null, 'adet', false, 6098),
  ('atistirmalik', 'Nestle KitKat', 'nestle-kitkat-4lu', 'Nestle', '4''lü', 'Çıtır gofret katları sütlü çikolatayla kaplı bar.', 79.90, null, 'paket', false, 6099),
  ('atistirmalik', 'Nestle Lion Bar', 'nestle-lion-bar-42-g', 'Nestle', '42 g', 'Karamelli ve çıtır tahıllı çikolata kaplı bar.', 24.90, null, 'adet', false, 6100),
  ('atistirmalik', 'Eti Wanted Fındıklı Bar', 'eti-wanted-findikli-bar-40-g', 'Eti', '40 g', 'Fındık parçacıklı, çikolata kaplı enerji barı.', 27.90, null, 'adet', false, 6101),
  ('atistirmalik', 'Eti Tutku Kremalı Bisküvi', 'eti-tutku-kremali-biskuvi-82-g', 'Eti', '82 g', 'Sütlü kremalı, çift kat sandviç bisküvi.', 22.90, null, 'adet', false, 6102),
  ('atistirmalik', 'Eti Puf Fındıklı', 'eti-puf-findikli-6li', 'Eti', '6''lı', 'Fındık kremalı, çikolata kaplı puf bisküvi.', 44.90, null, 'paket', false, 6103),
  ('atistirmalik', 'Eti Browni Karamelli', 'eti-browni-karamelli-8li', 'Eti', '8''li', 'Karamel dolgulu, yumuşak dokulu browni kek.', 64.90, null, 'paket', false, 6104),
  ('atistirmalik', 'Eti Cin Fındıklı', 'eti-cin-findikli-300-g', 'Eti', '300 g', 'Fındıklı kremayla doldurulmuş, klasik gofret atıştırmalık.', 46.90, null, 'adet', false, 6105),
  ('atistirmalik', 'Dankek Kremalı Rulo Kek', 'dankek-kremali-rulo-kek-6li', 'Dankek', '6''lı', 'Vanilya kremalı, rulo formunda yumuşak kek.', 54.90, null, 'paket', false, 6106),
  ('atistirmalik', 'Dankek Baton Kek Fındıklı', 'dankek-baton-kek-findikli-adet', 'Dankek', '60 g', 'Fındık parçacıklı, tekli baton kek.', 16.90, null, 'adet', false, 6107),
  ('atistirmalik', 'Hobby Sütlü Bar', 'hobby-sutlu-bar-33-g', 'Hobby', '33 g', 'Sütlü çikolata kaplı, karamelli enerji barı.', 19.90, null, 'adet', false, 6108),
  ('atistirmalik', 'Solen Big Baton Fındıklı', 'solen-big-baton-findikli-40-g', 'Solen', '40 g', 'Fındık parçacıklı, çikolatayla kaplı büyük baton.', 22.90, null, 'adet', false, 6109),
  ('atistirmalik', 'Ülker Çokoprens Mini', 'ulker-cokoprens-mini-6li', 'Ülker', '6''lı', 'Kakaolu kremalı, mini boy çokoprens paketi.', 49.90, null, 'paket', false, 6110),
  ('atistirmalik', 'Eti Form Bar Proteinli', 'eti-form-bar-proteinli-40-g', 'Eti', '40 g', 'Yulaflı, protein değeri yüksek diyet barı.', 29.90, null, 'adet', false, 6111),
  -- cikolata-sekerleme (20 yeni urun)
  ('cikolata-sekerleme', 'Milka Karamelli Tablet', 'milka-karamelli-tablet-100-g', 'Milka', '100 g', 'Karamel dolgulu, alpin sütlü çikolata tablet.', 79.90, null, 'adet', false, 6112),
  ('cikolata-sekerleme', 'Milka Choco Swing', 'milka-choco-swing-100-g', 'Milka', '100 g', 'Kakaolu bisküvi parçacıklı sütlü çikolata tablet.', 84.90, null, 'adet', false, 6113),
  ('cikolata-sekerleme', 'Toblerone Beyaz Çikolata', 'toblerone-beyaz-cikolata-100-g', 'Toblerone', '100 g', 'Bal ve bademli nugatlı, üçgen beyaz çikolata.', 129.90, null, 'adet', false, 6114),
  ('cikolata-sekerleme', 'Lindt Excellence Bitter %70', 'lindt-excellence-bitter-70-100-g', 'Lindt', '100 g', 'Yoğun kakao aromalı, %70 bitter çikolata tablet.', 149.90, null, 'adet', true, 6115),
  ('cikolata-sekerleme', 'Godiva Praline Kutu', 'godiva-praline-kutu-6li', 'Godiva', '6''lı', 'Şık kutuda sunulan, premium çikolata praline.', 349.90, null, 'paket', true, 6116),
  ('cikolata-sekerleme', 'Ferrero Rocher 8''li', 'ferrero-rocher-8li-kutu', 'Ferrero', '8''li', 'Fındıklı, çıtır gofretli hazelnut çikolata topları.', 179.90, null, 'paket', false, 6117),
  ('cikolata-sekerleme', 'Kinder Country', 'kinder-country-23-5-g', 'Kinder', '23,5 g', 'Tahıllı, sütlü çikolatayla kaplı atıştırmalık.', 24.90, null, 'adet', false, 6118),
  ('cikolata-sekerleme', 'Kinder Chocolate Mini', 'kinder-chocolate-mini-6li', 'Kinder', '6''lı', 'Sütlü dolgulu, mini boy çikolata baton.', 44.90, null, 'paket', false, 6119),
  ('cikolata-sekerleme', 'Nestle Aero Çikolata', 'nestle-aero-cikolata-90-g', 'Nestle', '90 g', 'Havadar dokulu, eriyen kabarcıklı sütlü çikolata.', 69.90, null, 'adet', false, 6120),
  ('cikolata-sekerleme', 'Eti Karam Fındıklı Çikolata', 'eti-karam-findikli-cikolata-60-g', 'Eti', '60 g', 'Fındık parçacıklı, sütlü çikolata tablet.', 34.90, null, 'adet', false, 6121),
  ('cikolata-sekerleme', 'Ülker Kare Bitter Çikolata', 'ulker-kare-bitter-cikolata-60-g', 'Ülker', '60 g', 'Kare kırılımlı, yoğun kakaolu bitter çikolata.', 32.90, null, 'adet', false, 6122),
  ('cikolata-sekerleme', 'Damak Sütlü Fındıklı Çikolata', 'damak-sutlu-findikli-cikolata-65-g', 'Damak', '65 g', 'Bütün fındıklı, sütlü çikolata tablet.', 39.90, null, 'adet', false, 6123),
  ('cikolata-sekerleme', 'Solen Coco Draje', 'solen-coco-draje-80-g', 'Solen', '80 g', 'Hindistan cevizli, çikolata kaplı draje şeker.', 44.90, null, 'adet', false, 6124),
  ('cikolata-sekerleme', 'Haribo Starmix', 'haribo-starmix-175-g', 'Haribo', '175 g', 'Karışık meyve aromalı, jelibon şeker paketi.', 89.90, null, 'adet', false, 6125),
  ('cikolata-sekerleme', 'Haribo Twin Cherry', 'haribo-twin-cherry-160-g', 'Haribo', '160 g', 'Kiraz aromalı, ikili bağlı jelibon şeker.', 84.90, null, 'adet', false, 6126),
  ('cikolata-sekerleme', 'Chupa Chups Lolipop', 'chupa-chups-lolipop-10lu', 'Chupa Chups', '10''lu', 'Karışık meyve aromalı, saplı lolipop şeker.', 59.90, null, 'paket', false, 6127),
  ('cikolata-sekerleme', 'Vivident Sakız Karpuz', 'vivident-sakiz-karpuz-27-g', 'Vivident', '27 g', 'Karpuz aromalı, şekersiz sakız paketi.', 14.90, null, 'adet', false, 6128),
  ('cikolata-sekerleme', 'Kent Bonbon Karışık', 'kent-bonbon-karisik-500-g', 'Kent', '500 g', 'Karışık meyve aromalı, sert draje şeker karışımı.', 149.90, null, 'paket', false, 6129),
  ('cikolata-sekerleme', 'Elvan Lokum Fıstıklı', 'elvan-lokum-fistikli-350-g', 'Elvan', '350 g', 'Antep fıstıklı, geleneksel tarifle üretilen lokum.', 129.90, null, 'adet', false, 6130),
  ('cikolata-sekerleme', 'Koska Helva Kakaolu', 'koska-helva-kakaolu-350-g', 'Koska', '350 g', 'Kakao aromalı, tahin bazlı geleneksel helva.', 99.90, null, 'adet', false, 6131),
  -- kahve-cay (20 yeni urun)
  ('kahve-cay', 'Nescafe Azera Americano', 'nescafe-azera-americano-100-g', 'Nescafe', '100 g', 'Kavrulmuş çekirdekten üretilen, yoğun aromalı hazır kahve.', 189.90, null, 'adet', false, 6132),
  ('kahve-cay', 'Jacobs Krönung', 'jacobs-kronung-200-g', 'Jacobs', '200 g', 'Zengin aromalı, filtre kahve için öğütülmüş kahve.', 219.90, null, 'adet', false, 6133),
  ('kahve-cay', 'Starbucks Espresso Roast Kapsül', 'starbucks-espresso-roast-kapsul-10lu', 'Starbucks', '10''lu', 'Yoğun kavrulmuş, espresso makinelerine uyumlu kapsül.', 199.90, null, 'paket', true, 6134),
  ('kahve-cay', 'Lavazza Qualita Oro Çekirdek', 'lavazza-qualita-oro-cekirdek-250-g', 'Lavazza', '250 g', 'Dengeli aromalı, İtalyan usulü çekirdek kahve.', 349.90, null, 'adet', false, 6135),
  ('kahve-cay', 'Kurukahveci Mehmet Efendi Sade Türk Kahvesi', 'mehmet-efendi-sade-turk-kahvesi-500-g', 'Kurukahveci Mehmet Efendi', '500 g', 'Geleneksel öğütüm, ailelik boy sade Türk kahvesi.', 289.90, null, 'adet', true, 6136),
  ('kahve-cay', 'Kahve Dünyası Fındıklı Türk Kahvesi', 'kahve-dunyasi-findikli-turk-kahvesi-250-g', 'Kahve Dünyası', '250 g', 'Fındık aromalı, özel harmanlı Türk kahvesi.', 179.90, null, 'adet', false, 6137),
  ('kahve-cay', 'Çaykur Tomurcuk Çay Dökme', 'caykur-tomurcuk-cay-dokme-1-kg', 'Çaykur', '1 kg', 'Taze tomurcuk yapraklardan üretilen dökme siyah çay.', 219.90, null, 'kg', false, 6138),
  ('kahve-cay', 'Doğuş Çaykolik Poşet Çay', 'dogus-caykolik-poset-cay-100lu', 'Doğuş', '100''lü', 'Günlük demlemeye uygun, ekonomik boy poşet çay.', 149.90, null, 'paket', false, 6139),
  ('kahve-cay', 'Lipton Earl Grey Bardak Poşet', 'lipton-earl-grey-bardak-poset-25li', 'Lipton', '25''li', 'Bergamot aromalı, siyah çay bardak poşeti.', 89.90, null, 'paket', false, 6140),
  ('kahve-cay', 'Ahmad Tea English Breakfast', 'ahmad-tea-english-breakfast-25li', 'Ahmad Tea', '25''li', 'İngiliz usulü harmanlanmış, yoğun aromalı siyah çay.', 149.90, null, 'paket', false, 6141),
  ('kahve-cay', 'Doğadan Karışık Meyve Çayı', 'dogadan-karisik-meyve-cayi-20li', 'Doğadan', '20''li', 'Elma, portakal ve tarçın aromalı meyve çayı.', 64.90, null, 'paket', false, 6142),
  ('kahve-cay', 'Twinings Yeşil Çay Yasemin', 'twinings-yesil-cay-yasemin-20li', 'Twinings', '20''li', 'Yasemin çiçeği aromalı, hafif demli yeşil çay.', 129.90, null, 'paket', false, 6143),
  ('kahve-cay', 'Nescafe 3ü1 Arada Sütlü Az Şekerli', 'nescafe-3u1-sutlu-az-sekerli-10lu', 'Nescafe', '10x14 g', 'Az şekerli, pratik hazır kahve saşesi.', 69.90, null, 'paket', false, 6144),
  ('kahve-cay', 'Tchibo Espresso Çekirdek', 'tchibo-espresso-cekirdek-500-g', 'Tchibo', '500 g', 'Koyu kavrulmuş, espresso makinesine uygun çekirdek kahve.', 349.90, null, 'adet', false, 6145),
  ('kahve-cay', 'Segafredo Espresso Kapsül', 'segafredo-espresso-kapsul-10lu', 'Segafredo', '10''lu', 'İtalyan usulü kavrulmuş, espresso kapsülü.', 179.90, null, 'paket', false, 6146),
  ('kahve-cay', 'Kahve Dünyası Soğuk Kahve Karamelli', 'kahve-dunyasi-soguk-kahve-karamelli-250-ml', 'Kahve Dünyası', '250 ml', 'Karamel aromalı, hazır içilebilir soğuk kahve.', 59.90, null, 'adet', false, 6147),
  ('kahve-cay', 'Nescafe Frappe Buzlu Kahve', 'nescafe-frappe-buzlu-kahve-250-ml', 'Nescafe', '250 ml', 'Köpüklü ve serinletici, hazır buzlu kahve içeceği.', 54.90, null, 'adet', false, 6148),
  ('kahve-cay', 'Çaykur Elit Çay', 'caykur-elit-cay-1-kg', 'Çaykur', '1 kg', 'Seçme yapraklardan üretilen, üstün kalite dökme çay.', 249.90, null, 'kg', false, 6149),
  ('kahve-cay', 'Kekik ve Nane Bitki Çayı', 'kekik-nane-bitki-cayi-20li', '', '20''li', 'Ferahlatıcı, kekik ve nane karışımı bitki çayı.', 49.90, null, 'paket', false, 6150),
  ('kahve-cay', 'Değirmen Öğütülmüş Filtre Kahve', 'degirmen-ogutulmus-filtre-kahve-250-g', 'Değirmen', '250 g', 'Orta kavrulmuş, filtre kahve makinelerine uygun öğütüm.', 149.90, null, 'adet', false, 6151),
  -- dondurma (18 yeni urun)
  ('dondurma', 'Algida Magnum Double Chocolate', 'algida-magnum-double-chocolate-4lu', 'Algida', '4''lü', 'Çift kat çikolatalı, çıtır kaplamalı külahsız dondurma.', 189.90, null, 'paket', true, 6152),
  ('dondurma', 'Algida Cornetto Fıstıklı', 'algida-cornetto-fistikli-4lu', 'Algida', '4''lü', 'Fıstık sosu ve parçacıklı, gofret külahlı dondurma.', 129.90, null, 'paket', false, 6153),
  ('dondurma', 'Algida Solero Meyveli', 'algida-solero-meyveli-4lu', 'Algida', '4''lü', 'Meyve sorbesi ve kremalı, çubuk formunda dondurma.', 119.90, null, 'paket', false, 6154),
  ('dondurma', 'Haagen-Dazs Vanilya', 'haagen-dazs-vanilya-460-ml', 'Haagen-Dazs', '460 ml', 'Yoğun kremalı, premium vanilyalı kutu dondurma.', 349.90, null, 'adet', true, 6155),
  ('dondurma', 'Mado Fıstıklı Kutu', 'mado-fistikli-kutu-1-l', 'Mado', '1 L', 'Antep fıstıklı, geleneksel dövme dondurma.', 219.90, null, 'adet', false, 6156),
  ('dondurma', 'Mado Çikolatalı Külah', 'mado-cikolatali-kulah-adet', 'Mado', '120 ml', 'Yoğun çikolata aromalı, tek porsiyon külah dondurma.', 59.90, null, 'adet', false, 6157),
  ('dondurma', 'Özsüt Karamelli Kutu', 'ozsut-karamelli-kutu-750-ml', 'Özsüt', '750 ml', 'Karamel soslu, kremamsı dokulu kutu dondurma.', 179.90, null, 'adet', false, 6158),
  ('dondurma', 'Golf Çikolatalı Külah', 'golf-cikolatali-kulah-4lu', 'Golf', '4''lü', 'Çikolata kaplı, gofret külahlı aile boy dondurma.', 89.90, null, 'paket', false, 6159),
  ('dondurma', 'Golf Meyveli Buz Çubuk', 'golf-meyveli-buz-cubuk-8li', 'Golf', '8''li', 'Karışık meyve aromalı, serinletici buz çubuğu.', 79.90, null, 'paket', false, 6160),
  ('dondurma', 'Panda Limonlu Buz', 'panda-limonlu-buz-6li', 'Panda', '6''lı', 'Ekşimsi limon aromalı, buz çubuğu paketi.', 59.90, null, 'paket', false, 6161),
  ('dondurma', 'Frigo Maraş Usulü Kutu', 'frigo-maras-usulu-kutu-500-g', 'Frigo', '500 g', 'Sakızımsı dokulu, geleneksel Maraş usulü dondurma.', 99.90, null, 'adet', false, 6162),
  ('dondurma', 'Cornetto Fındıklı', 'cornetto-findikli-120-ml', 'Cornetto', '120 ml', 'Fındık sosu katmanlı, gofret külahlı dondurma.', 34.90, null, 'adet', false, 6163),
  ('dondurma', 'Magnum Beyaz Çilekli', 'magnum-beyaz-cilekli-3lu', 'Magnum', '3''lü', 'Çilek soslu, beyaz çikolata kaplamalı dondurma çubuğu.', 149.90, null, 'paket', false, 6164),
  ('dondurma', 'Meyveli Su Buz Karpuz', 'meyveli-su-buz-karpuz-6li', '', '6''lı', 'Yaz için ferahlatıcı, karpuz aromalı su buzu.', 44.90, null, 'paket', false, 6165),
  ('dondurma', 'Vişne Sos Dondurma Üstü', 'visne-sos-dondurma-ustu-200-g', '', '200 g', 'Dondurma ve waffle için ekşimsi vişne sosu.', 44.90, null, 'adet', false, 6166),
  ('dondurma', 'Waffle Dondurma Sandviç', 'waffle-dondurma-sandvic-4lu', '', '4''lü', 'İki waffle arasında kremalı dondurma sandviçi.', 89.90, null, 'paket', false, 6167),
  ('dondurma', 'Antep Fıstıklı Kaymak Dondurma Kutu', 'antep-fistikli-kaymak-dondurma-kutu-500-g', '', '500 g', 'Kaymak dokulu, bol Antep fıstıklı kutu dondurma.', 149.90, null, 'adet', false, 6168),
  ('dondurma', 'Sade Kaymaklı Dondurma Külah', 'sade-kaymakli-dondurma-kulah-4lu', '', '4''lü', 'Geleneksel tarifle üretilen, kaymaklı külah dondurma.', 99.90, null, 'paket', false, 6169),
  -- donuk-gida (18 yeni urun)
  ('donuk-gida', 'Superfresh Tavuklu Pizza', 'superfresh-tavuklu-pizza-400-g', 'Superfresh', '400 g', 'Izgara tavuklu, fırına hazır donuk pizza.', 149.90, null, 'adet', false, 6170),
  ('donuk-gida', 'Dr. Oetker Ristorante Mozzarella', 'dr-oetker-ristorante-mozzarella-335-g', 'Dr. Oetker', '335 g', 'Bol mozzarella peynirli, ince hamurlu İtalyan pizza.', 189.90, null, 'adet', false, 6171),
  ('donuk-gida', 'Pınar Köfte Sote Donuk', 'pinar-kofte-sote-donuk-450-g', 'Pınar', '450 g', 'Soslu, ısıtılıp servis edilen köfte sote.', 139.90, null, 'adet', false, 6172),
  ('donuk-gida', 'Banvit Tavuk Baget Marine Donuk', 'banvit-tavuk-baget-marine-donuk-900-g', 'Banvit', '900 g', 'Baharatlı marine edilmiş, fırınlık tavuk baget.', 189.90, null, 'adet', false, 6173),
  ('donuk-gida', 'Superfresh Fırın Sebze Karışımı', 'superfresh-firin-sebze-karisimi-450-g', 'Superfresh', '450 g', 'Fırına hazır, renkli donuk sebze karışımı.', 74.90, null, 'adet', false, 6174),
  ('donuk-gida', 'Ekol Ahtapot Halka Donuk', 'ekol-ahtapot-halka-donuk-400-g', 'Ekol', '400 g', 'Temizlenmiş, halka kesim donuk ahtapot.', 249.90, null, 'adet', false, 6175),
  ('donuk-gida', 'Reis Donuk Enginar', 'reis-donuk-enginar-450-g', 'Reis', '450 g', 'Ayıklanmış, zeytinyağlı yemeğe hazır donuk enginar.', 119.90, null, 'adet', false, 6176),
  ('donuk-gida', 'Superfresh Çilek Dilim Donuk', 'superfresh-cilek-dilim-donuk-450-g', 'Superfresh', '450 g', 'Smoothie ve tatlılık, dilim kesim donuk çilek.', 69.90, null, 'adet', false, 6177),
  ('donuk-gida', 'Superfresh Vişne Donuk', 'superfresh-visne-donuk-450-g', 'Superfresh', '450 g', 'Çekirdeği çıkarılmış, tatlılık donuk vişne.', 74.90, null, 'adet', false, 6178),
  ('donuk-gida', 'Kuzey Somon Fileto Donuk', 'kuzey-somon-fileto-donuk-400-g', 'Kuzey', '400 g', 'Kılçıksız, ızgaralık donuk somon fileto.', 299.90, null, 'adet', true, 6179),
  ('donuk-gida', 'Dr. Oetker Mini Pizza Snack', 'dr-oetker-mini-pizza-snack-250-g', 'Dr. Oetker', '250 g', 'Atıştırmalık boy, fırına hazır mini pizza.', 99.90, null, 'adet', false, 6180),
  ('donuk-gida', 'Ispanaklı Poğaça Donuk', 'ispanakli-pogaca-donuk-500-g', '', '500 g', 'İçi bol ıspanaklı, fırına hazır donuk poğaça.', 79.90, null, 'adet', false, 6181),
  ('donuk-gida', 'Kabak Mücver Donuk', 'kabak-mucver-donuk-500-g', '', '500 g', 'Kızartmaya hazır, kabaklı donuk mücver.', 69.90, null, 'adet', false, 6182),
  ('donuk-gida', 'Etli Ekmek Donuk', 'etli-ekmek-donuk-400-g', '', '400 g', 'Kıymalı, fırına hazır ince hamurlu etli ekmek.', 89.90, null, 'adet', false, 6183),
  ('donuk-gida', 'Tavuk Şinitzel Donuk', 'tavuk-sinitzel-donuk-500-g', '', '500 g', 'Galeta unlu, kızartmaya hazır donuk tavuk şinitzel.', 119.90, null, 'adet', false, 6184),
  ('donuk-gida', 'Mantarlı Kroket Donuk', 'mantarli-kroket-donuk-400-g', '', '400 g', 'Kremalı mantar dolgulu, kızartmaya hazır kroket.', 69.90, null, 'adet', false, 6185),
  ('donuk-gida', 'Waffle Mini Donuk', 'waffle-mini-donuk-300-g', '', '300 g', 'Tost makinesinde ısıtılan, mini boy donuk waffle.', 59.90, null, 'adet', false, 6186),
  ('donuk-gida', 'Somon Burger Donuk', 'somon-burger-donuk-300-g', '', '300 g', 'Izgaraya hazır, somon etinden burger köftesi.', 149.90, null, 'adet', false, 6187),
  -- zeytin-tursu (16 yeni urun)
  ('zeytin-tursu', 'Marmarabirlik Kahvaltılık Yeşil Zeytin', 'marmarabirlik-kahvaltilik-yesil-zeytin-700-g', 'Marmarabirlik', '700 g', 'İri taneli, kahvaltılık yeşil zeytin.', 249.90, null, 'adet', false, 6188),
  ('zeytin-tursu', 'Tariş Gemlik Siyah Zeytin', 'taris-gemlik-siyah-zeytin-800-g', 'Tariş', '800 g', 'Gemlik cinsi, az tuzlu siyah zeytin.', 279.90, null, 'adet', false, 6189),
  ('zeytin-tursu', 'Komili Zeytin Ezmesi Acılı', 'komili-zeytin-ezmesi-acili-200-g', 'Komili', '200 g', 'Acı biberli, mezelik siyah zeytin ezmesi.', 79.90, null, 'adet', false, 6190),
  ('zeytin-tursu', 'Beşler Salatalık Turşusu', 'besler-salatalik-tursusu-720-g', 'Beşler', '720 g', 'Küçük taneli, çıtır salatalık turşusu.', 69.90, null, 'adet', false, 6191),
  ('zeytin-tursu', 'Beşler Karışık Turşu', 'besler-karisik-tursu-1500-g', 'Beşler', '1500 g', 'Ailelik boy, çeşitli sebzelerden karışık turşu.', 129.90, null, 'adet', false, 6192),
  ('zeytin-tursu', 'Tamek Havuç Turşusu', 'tamek-havuc-tursusu-720-g', 'Tamek', '720 g', 'Dilimlenmiş, çıtır havuç turşusu.', 74.90, null, 'adet', false, 6193),
  ('zeytin-tursu', 'Doğanay Şalgam Suyu Acısız', 'doganay-salgam-suyu-acisiz-1-l', 'Doğanay', '1 L', 'Ekşi aromalı, geleneksel usulde fermente şalgam suyu.', 49.90, null, 'adet', false, 6194),
  ('zeytin-tursu', 'Efsane Şalgam Suyu Acılı', 'efsane-salgam-suyu-acili-1-l', 'Efsane', '1 L', 'Acı biberli, koyu kıvamlı şalgam suyu.', 44.90, null, 'adet', false, 6195),
  ('zeytin-tursu', 'Erikli Şalgam Suyu Acılı', 'erikli-salgam-suyu-acili-330-ml', 'Erikli', '330 ml', 'Tek kişilik şişede, acılı şalgam suyu.', 24.90, null, 'adet', false, 6196),
  ('zeytin-tursu', 'Pancar Turşusu', 'pancar-tursusu-720-g', '', '720 g', 'Mor renkli, ekşimsi lezzette pancar turşusu.', 59.90, null, 'adet', false, 6197),
  ('zeytin-tursu', 'Yeşil Domates Turşusu', 'yesil-domates-tursusu-720-g', '', '720 g', 'Olgunlaşmamış domatesten, çıtır turşu.', 64.90, null, 'adet', false, 6198),
  ('zeytin-tursu', 'Enginar Turşusu', 'enginar-tursusu-500-g', '', '500 g', 'Mezelik, taze enginardan hazırlanmış turşu.', 89.90, null, 'adet', false, 6199),
  ('zeytin-tursu', 'Zeytinyağlı Yeşil Zeytin Kavurma', 'zeytinyagli-yesil-zeytin-kavurma-300-g', '', '300 g', 'Sarımsaklı, zeytinyağında kavrulmuş yeşil zeytin mezesi.', 74.90, null, 'adet', false, 6200),
  ('zeytin-tursu', 'Sarımsaklı Zeytin Ezmesi', 'sarimsakli-zeytin-ezmesi-200-g', '', '200 g', 'Sarımsak aromalı, kahvaltılık zeytin ezmesi.', 69.90, null, 'adet', false, 6201),
  ('zeytin-tursu', 'Yaprak Sarma Zeytinyağlı Ev Yapımı', 'yaprak-sarma-zeytinyagli-ev-yapimi-400-g', '', '400 g', 'Bağ yaprağından, geleneksel usulde zeytinyağlı sarma.', 89.90, null, 'adet', false, 6202),
  ('zeytin-tursu', 'Portakallı Zeytin Salatası', 'portakalli-zeytin-salatasi-300-g', '', '300 g', 'Portakal ve zeytinyağıyla hazırlanan mezelik zeytin salatası.', 79.90, null, 'adet', false, 6203),
  -- temizlik-deterjan (20 yeni urun)
  ('temizlik-deterjan', 'Ariel Kapsül Deterjan 3''ü1 Arada', 'ariel-kapsul-deterjan-3u1-38-yikama', 'Ariel', '38 yıkama', 'Leke çıkarıcı ve yumuşatıcı içeren üçlü kapsül deterjan.', 349.90, null, 'adet', true, 6204),
  ('temizlik-deterjan', 'Persil Kapsül Deterjan Gül', 'persil-kapsul-deterjan-gul-30-yikama', 'Persil', '30 yıkama', 'Gül kokulu, tek kullanımlık kapsül çamaşır deterjanı.', 299.90, null, 'adet', false, 6205),
  ('temizlik-deterjan', 'Omo Sıvı Deterjan Siyahlar', 'omo-sivi-deterjan-siyahlar-2-7-l', 'Omo', '2,7 L', 'Siyah ve koyu renkli kıyafetler için sıvı deterjan.', 219.90, null, 'adet', false, 6206),
  ('temizlik-deterjan', 'Bingo Toz Deterjan Beyazlar', 'bingo-toz-deterjan-beyazlar-8-kg', 'Bingo', '8 kg', 'Ailelik boy, beyazlar için lekeye karşı etkili toz deterjan.', 389.90, null, 'adet', false, 6207),
  ('temizlik-deterjan', 'Fairy Bulaşık Makinesi Jel Tablet', 'fairy-bulasik-makinesi-jel-tablet-45li', 'Fairy', '45''li', 'Yağ çözücü formüllü, bulaşık makinesi jel tableti.', 349.90, null, 'paket', false, 6208),
  ('temizlik-deterjan', 'Finish Bulaşık Makinesi Jeli', 'finish-bulasik-makinesi-jeli-1-l', 'Finish', '1 L', 'Parlak sonuç veren, sıvı bulaşık makinesi deterjanı.', 179.90, null, 'adet', false, 6209),
  ('temizlik-deterjan', 'Domestos Tuvalet Kazıyıcı Jel', 'domestos-tuvalet-kaziyici-jel-750-ml', 'Domestos', '750 ml', 'Kireç ve leke sökücü, yoğun kıvamlı WC jeli.', 89.90, null, 'adet', false, 6210),
  ('temizlik-deterjan', 'Bref WC Örümcek Ağı Önleyici', 'bref-wc-orumcek-agi-onleyici-50-g', 'Bref', '50 g', 'Uzun süre koku bırakan, asılı WC bloğu.', 44.90, null, 'adet', false, 6211),
  ('temizlik-deterjan', 'Cif Cam ve Yüzey Temizleyici Sprey', 'cif-cam-yuzey-temizleyici-sprey-750-ml', 'Cif', '750 ml', 'İz bırakmayan, cam ve yüzeyler için temizleyici sprey.', 64.90, null, 'adet', false, 6212),
  ('temizlik-deterjan', 'Vanish Oxi Action Leke Çıkarıcı Toz', 'vanish-oxi-action-leke-cikarici-toz-500-g', 'Vanish', '500 g', 'Oksijen destekli, güçlü leke çıkarıcı toz takviye.', 249.90, null, 'adet', false, 6213),
  ('temizlik-deterjan', 'Vernel Yumuşatıcı Konsantre Deniz Esintisi', 'vernel-yumusatici-konsantre-deniz-esintisi-1440-ml', 'Vernel', '1440 ml', 'Uzun süre kokan, konsantre çamaşır yumuşatıcısı.', 149.90, null, 'adet', false, 6214),
  ('temizlik-deterjan', 'Yumoş Parfüm Boncuğu Okyanus', 'yumos-parfum-boncugu-okyanus-180-g', 'Yumoş', '180 g', 'Çamaşırlara uzun süreli koku katan parfüm boncuğu.', 89.90, null, 'adet', false, 6215),
  ('temizlik-deterjan', 'Glade Oda Kokusu Sprey Lavanta', 'glade-oda-kokusu-sprey-lavanta-300-ml', 'Glade', '300 ml', 'Lavanta kokulu, anında etkili oda spreyi.', 99.90, null, 'adet', false, 6216),
  ('temizlik-deterjan', 'Air Wick Elektrikli Oda Kokusu Yedek', 'air-wick-elektrikli-oda-kokusu-yedek-19-ml', 'Air Wick', '19 ml', 'Elektrikli cihaz için yedek oda kokusu şişesi.', 89.90, null, 'adet', false, 6217),
  ('temizlik-deterjan', 'Mr. Muscle Fırın ve Ocak Temizleyici', 'mr-muscle-firin-ocak-temizleyici-500-ml', 'Mr. Muscle', '500 ml', 'Yanık yağ lekelerini çözen, güçlü fırın temizleyici.', 99.90, null, 'adet', false, 6218),
  ('temizlik-deterjan', 'Cillit Bang Siyah Küf Sökücü', 'cillit-bang-siyah-kuf-sokucu-750-ml', 'Cillit Bang', '750 ml', 'Banyo derzlerindeki küfü etkili şekilde temizler.', 119.90, null, 'adet', false, 6219),
  ('temizlik-deterjan', 'Duck WC Blok Aktif Temiz', 'duck-wc-blok-aktif-temiz-3lu', 'Duck', '3''lü', 'Her sifonda köpüren, uzun etkili WC bloğu.', 74.90, null, 'paket', false, 6220),
  ('temizlik-deterjan', 'Woolite Hassas Yıkama Deterjanı', 'woolite-hassas-yikama-deterjani-900-ml', 'Woolite', '900 ml', 'Yünlü ve hassas kumaşlar için özel sıvı deterjan.', 179.90, null, 'adet', false, 6221),
  ('temizlik-deterjan', 'Detan Bulaşık Makinesi Tuzu', 'detan-bulasik-makinesi-tuzu-1-5-kg', 'Detan', '1,5 kg', 'Kireç önleyici, bulaşık makinesi için su yumuşatıcı tuz.', 89.90, null, 'adet', false, 6222),
  ('temizlik-deterjan', 'Scotch-Brite Yer Paspası Yedek Başlık', 'scotch-brite-yer-paspasi-yedek-baslik-adet', 'Scotch-Brite', '1 adet', 'Mikrofiber dokulu, yer paspası için yedek başlık.', 69.90, null, 'adet', false, 6223),
  -- kagit-urunleri (16 yeni urun)
  ('kagit-urunleri', 'Selpak Islak Havlu Bebek', 'selpak-islak-havlu-bebek-3x56', 'Selpak', '3x56 adet', 'Alkolsüz formüllü, bebek cildine uygun ıslak havlu.', 99.90, null, 'paket', false, 6224),
  ('kagit-urunleri', 'Solo Aile Boy Tuvalet Kağıdı', 'solo-aile-boy-tuvalet-kagidi-40li', 'Solo', '40''lı', 'Ekonomik ailelik boy, yumuşak dokulu tuvalet kağıdı.', 259.90, null, 'paket', false, 6225),
  ('kagit-urunleri', 'Familia Prestij Kağıt Havlu', 'familia-prestij-kagit-havlu-10lu', 'Familia', '10''lu', 'Üç katlı, emici prestij kağıt havlu paketi.', 149.90, null, 'paket', false, 6226),
  ('kagit-urunleri', 'Focus Islak Mendil', 'focus-islak-mendil-90li', 'Focus', '90''lı', 'Cilde nazik, çok amaçlı ıslak mendil paketi.', 44.90, null, 'paket', false, 6227),
  ('kagit-urunleri', 'Papia Peçete Desenli', 'papia-pecete-desenli-100lu', 'Papia', '100''lü', 'Sofra ve mutfak için desenli kağıt peçete.', 44.90, null, 'paket', false, 6228),
  ('kagit-urunleri', 'Nice Tuvalet Kağıdı', 'nice-tuvalet-kagidi-32li', 'Nice', '32''li', 'Üç katlı, yumuşak dokulu tuvalet kağıdı.', 289.90, null, 'paket', false, 6229),
  ('kagit-urunleri', 'Hayat Kağıt Havlu', 'hayat-kagit-havlu-6li', 'Hayat', '6''lı', 'Emici ve dayanıklı, çok amaçlı kağıt havlu.', 79.90, null, 'paket', false, 6230),
  ('kagit-urunleri', 'Silveks Peçete', 'silveks-pecete-100lu', 'Silveks', '100''lü', 'Yumuşak dokulu, günlük kullanım kağıt peçete.', 34.90, null, 'paket', false, 6231),
  ('kagit-urunleri', 'Kleenex Kutu Mendil', 'kleenex-kutu-mendil-3lu', 'Kleenex', '3''lü', 'Balsamlı, cilde yumuşak kutu mendil paketi.', 89.90, null, 'paket', false, 6232),
  ('kagit-urunleri', 'Bebem Islak Mendil', 'bebem-islak-mendil-4x56', 'Bebem', '4x56 adet', 'Parfümsüz, hassas cilt için ıslak mendil.', 79.90, null, 'paket', false, 6233),
  ('kagit-urunleri', 'Servis Kağıt Bardak Altlığı', 'servis-kagit-bardak-altligi-100lu', 'Servis', '100''lü', 'Kafe ve ev kullanımına uygun bardak altlığı.', 39.90, null, 'paket', false, 6234),
  ('kagit-urunleri', 'Selpak Ultra Tuvalet Kağıdı', 'selpak-ultra-tuvalet-kagidi-24lu', 'Selpak', '24''lü', 'Üç katlı, yüksek emicilikte ultra tuvalet kağıdı.', 259.90, null, 'paket', false, 6235),
  ('kagit-urunleri', 'Papia Comfort Kağıt Havlu', 'papia-comfort-kagit-havlu-4lu', 'Papia', '4''lü', 'Yumuşak dokulu, güçlü emici kağıt havlu.', 84.90, null, 'paket', false, 6236),
  ('kagit-urunleri', 'Familia Islak Tuvalet Kağıdı', 'familia-islak-tuvalet-kagidi-42li', 'Familia', '42''li', 'Ekstra temizlik için ıslak tuvalet kağıdı yedeği.', 69.90, null, 'paket', false, 6237),
  ('kagit-urunleri', 'Solo Peçete Kokteyl', 'solo-pecete-kokteyl-200lu', 'Solo', '200''lü', 'Küçük boy, kokteyl ve davetler için peçete.', 59.90, null, 'paket', false, 6238),
  ('kagit-urunleri', 'Selpak Kutu Mendil Aile Boy', 'selpak-kutu-mendil-aile-boy-200lu', 'Selpak', '200''lü', 'Büyük boy, uzun süre yeten kutu mendil.', 64.90, null, 'paket', false, 6239),
  -- kisisel-bakim (20 yeni urun)
  ('kisisel-bakim', 'TRESemmé Şampuan Keratin Onarım', 'tresemme-sampuan-keratin-onarim-500-ml', 'TRESemmé', '500 ml', 'Keratin içerikli, yıpranmış saçlar için onarıcı şampuan.', 149.90, null, 'adet', false, 6240),
  ('kisisel-bakim', 'L''Oréal Paris Elvive Şampuan', 'loreal-paris-elvive-sampuan-450-ml', 'L''Oréal Paris', '450 ml', 'Dökülme karşıtı, güçlendirici formüllü şampuan.', 159.90, null, 'adet', false, 6241),
  ('kisisel-bakim', 'Herbal Essences Şampuan Aloe Vera', 'herbal-essences-sampuan-aloe-vera-400-ml', 'Herbal Essences', '400 ml', 'Bitkisel özlü, nemlendirici aloe vera şampuanı.', 139.90, null, 'adet', false, 6242),
  ('kisisel-bakim', 'Nivea Men Şampuan 3''ü1 Arada', 'nivea-men-sampuan-3u1-arada-400-ml', 'Nivea', '400 ml', 'Saç, sakal ve vücut için üçü bir arada şampuan.', 119.90, null, 'adet', false, 6243),
  ('kisisel-bakim', 'Dove Erkek Duş Jeli Care', 'dove-erkek-dus-jeli-care-500-ml', 'Dove', '500 ml', 'Nemlendirici formüllü, erkeklere özel duş jeli.', 129.90, null, 'adet', false, 6244),
  ('kisisel-bakim', 'Rexona Kadın Deo Sprey Musk', 'rexona-kadin-deo-sprey-musk-150-ml', 'Rexona', '150 ml', '48 saat koruma sağlayan, misk kokulu deodorant.', 89.90, null, 'adet', false, 6245),
  ('kisisel-bakim', 'Nivea Men Deo Roll-on Silver Protect', 'nivea-men-deo-rollon-silver-protect-50-ml', 'Nivea', '50 ml', 'Gümüş iyonlu, ter kokusunu önleyen roll-on deodorant.', 79.90, null, 'adet', false, 6246),
  ('kisisel-bakim', 'Colgate Max White Diş Macunu', 'colgate-max-white-dis-macunu-100-ml', 'Colgate', '100 ml', 'Beyazlatıcı formüllü, günlük kullanım diş macunu.', 89.90, null, 'adet', false, 6247),
  ('kisisel-bakim', 'Signal Kids Diş Macunu Çilekli', 'signal-kids-dis-macunu-cilekli-50-ml', 'Signal', '50 ml', 'Çocuklar için çilek aromalı, florürlü diş macunu.', 49.90, null, 'adet', false, 6248),
  ('kisisel-bakim', 'Oral-B Şarjlı Diş Fırçası Yedek Başlık', 'oral-b-sarjli-dis-fircasi-yedek-baslik-2li', 'Oral-B', '2''li', 'Şarjlı diş fırçaları için yedek fırça başlığı.', 149.90, null, 'paket', false, 6249),
  ('kisisel-bakim', 'Gillette Venus Kadın Tıraş Bıçağı', 'gillette-venus-kadin-tras-bicagi-4lu', 'Gillette', '4''lü', 'Kayan şeritli, hassas cilt için kadın tıraş bıçağı.', 219.90, null, 'paket', false, 6250),
  ('kisisel-bakim', 'Veet Ilık Vaks Bandı', 'veet-ilik-vaks-bandi-20li', 'Veet', '20''li', 'Kolay uygulanan, tüy alma için hazır vaks bandı.', 179.90, null, 'paket', false, 6251),
  ('kisisel-bakim', 'Molped Gece Ped Kanatlı', 'molped-gece-ped-kanatli-8li', 'Molped', '8''li', 'Ekstra emici, kanatlı gece hijyenik pedi.', 44.90, null, 'paket', false, 6252),
  ('kisisel-bakim', 'Orkid Tampon Süper', 'orkid-tampon-super-16li', 'Orkid', '16''lı', 'Uygulayıcılı, süper emicilikte tampon.', 79.90, null, 'paket', false, 6253),
  ('kisisel-bakim', 'Vichy Normaderm Yüz Temizleme Jeli', 'vichy-normaderm-yuz-temizleme-jeli-200-ml', 'Vichy', '200 ml', 'Sivilceye eğilimli ciltler için arındırıcı temizleme jeli.', 249.90, null, 'adet', false, 6254),
  ('kisisel-bakim', 'Nivea Micellar Su', 'nivea-micellar-su-400-ml', 'Nivea', '400 ml', 'Makyaj temizleyici, üç etkili misel suyu.', 129.90, null, 'adet', false, 6255),
  ('kisisel-bakim', 'Garnier Micellar Temizleme Suyu', 'garnier-micellar-temizleme-suyu-400-ml', 'Garnier', '400 ml', 'Hassas ciltler için nazik misel temizleme suyu.', 119.90, null, 'adet', false, 6256),
  ('kisisel-bakim', 'Kolonya 4711 Orijinal', 'kolonya-4711-orijinal-400-ml', '4711', '400 ml', 'Ferahlatıcı narenciye kokulu, klasik Alman kolonyası.', 189.90, null, 'adet', false, 6257),
  ('kisisel-bakim', 'Eyüp Sabri Tuncer Limon Kolonyası', 'eyup-sabri-tuncer-limon-kolonyasi-400-ml', 'Eyüp Sabri Tuncer', '400 ml', 'Yüksek alkollü, ferahlatıcı limon kolonyası.', 79.90, null, 'adet', false, 6258),
  ('kisisel-bakim', 'Nivea Erkek Tıraş Sonrası Losyon', 'nivea-erkek-tras-sonrasi-losyon-100-ml', 'Nivea', '100 ml', 'Cildi yatıştıran, ferahlatıcı tıraş sonrası losyon.', 89.90, null, 'adet', false, 6259),
  -- vitamin-ilk-yardim (18 yeni urun)
  ('vitamin-ilk-yardim', 'Centrum Silver 50+ Multivitamin', 'centrum-silver-50-plus-multivitamin-30-tablet', 'Centrum', '30 tablet', '50 yaş üzeri için özel formüllü multivitamin.', 349.90, null, 'adet', false, 6260),
  ('vitamin-ilk-yardim', 'Supradyn Recharge Multivitamin', 'supradyn-recharge-multivitamin-30-tablet', 'Supradyn', '30 tablet', 'Enerji ve bağışıklık desteği için multivitamin.', 299.90, null, 'adet', false, 6261),
  ('vitamin-ilk-yardim', 'Solgar Magnezyum Sitrat', 'solgar-magnezyum-sitrat-60-tablet', 'Solgar', '60 tablet', 'Kas ve sinir sistemini destekleyen magnezyum takviyesi.', 279.90, null, 'adet', false, 6262),
  ('vitamin-ilk-yardim', 'Şifa D3 Vitamini Damla', 'sifa-d3-vitamini-damla-20-ml', 'Şifa', '20 ml', 'Kemik sağlığını destekleyen, damla formunda D3 vitamini.', 129.90, null, 'adet', false, 6263),
  ('vitamin-ilk-yardim', 'Venatura Çinko Pikolinat', 'venatura-cinko-pikolinat-60-tablet', 'Venatura', '60 tablet', 'Bağışıklık sistemini destekleyen çinko takviyesi.', 189.90, null, 'adet', false, 6264),
  ('vitamin-ilk-yardim', 'Panadol Extra', 'panadol-extra-500-mg-24-tablet', 'Panadol', '24 tablet', 'Ağrı kesici ve ateş düşürücü etkili tablet.', 69.90, null, 'adet', false, 6265),
  ('vitamin-ilk-yardim', 'Majezik', 'majezik-100-mg-10-tablet', 'Majezik', '10 tablet', 'Kas ve eklem ağrılarına yönelik ağrı kesici tablet.', 59.90, null, 'adet', false, 6266),
  ('vitamin-ilk-yardim', 'Talcid Antiasit Çiğneme Tableti', 'talcid-antiasit-cigneme-tableti-20li', 'Talcid', '20''li', 'Mide yanmasına karşı hızlı etkili çiğneme tableti.', 89.90, null, 'paket', false, 6267),
  ('vitamin-ilk-yardim', 'Fervex Soğuk Algınlığı Saşe', 'fervex-soguk-alginligi-sase-8li', 'Fervex', '8''li', 'Grip belirtilerini hafifleten, sıcak içilen saşe.', 149.90, null, 'paket', false, 6268),
  ('vitamin-ilk-yardim', 'Coldrex Grip Tablet', 'coldrex-grip-tablet-12li', 'Coldrex', '12''li', 'Nezle ve grip semptomlarına karşı kombine tablet.', 79.90, null, 'paket', false, 6269),
  ('vitamin-ilk-yardim', 'Bepanthol Derma Onarıcı Krem', 'bepanthol-derma-onarici-krem-100-ml', 'Bepanthol', '100 ml', 'Kuru ve hassas ciltler için onarıcı bakım kremi.', 249.90, null, 'adet', false, 6270),
  ('vitamin-ilk-yardim', 'Hansaplast Sivilce Bandı', 'hansaplast-sivilce-bandi-24lu', 'Hansaplast', '24''lü', 'Gece boyu etkili, görünmez sivilce bandı.', 69.90, null, 'paket', false, 6271),
  ('vitamin-ilk-yardim', 'Dettol Yara Dezenfektan Spreyi', 'dettol-yara-dezenfektan-spreyi-60-ml', 'Dettol', '60 ml', 'Yaralarda enfeksiyon riskini azaltan dezenfektan sprey.', 89.90, null, 'adet', false, 6272),
  ('vitamin-ilk-yardim', 'Batticon Yara Bandı Su Geçirmez', 'batticon-yara-bandi-su-gecirmez-10lu', 'Batticon', '10''lu', 'Duş alırken bile koruyan, su geçirmez yara bandı.', 49.90, null, 'paket', false, 6273),
  ('vitamin-ilk-yardim', 'Probiyotik Çocuk Şurup', 'probiyotik-cocuk-surup-150-ml', '', '150 ml', 'Sindirim sistemini destekleyen, çocuklara özel şurup.', 199.90, null, 'adet', false, 6274),
  ('vitamin-ilk-yardim', 'Melatonin Spreyi', 'melatonin-spreyi-20-ml', '', '20 ml', 'Uyku düzenine yardımcı, dilaltı melatonin spreyi.', 139.90, null, 'adet', false, 6275),
  ('vitamin-ilk-yardim', 'Ateş Düşürücü Jel Bandı Çocuk', 'ates-dusurucu-jel-bandi-cocuk-6li', '', '6''lı', 'Alına yapıştırılan, serinletici ateş düşürücü jel bandı.', 44.90, null, 'paket', false, 6276),
  ('vitamin-ilk-yardim', 'Tıbbi Boyunluk Ayarlanabilir', 'tibbi-boyunluk-ayarlanabilir-adet', '', '1 adet', 'Boyun ağrılarında destek için ayarlanabilir boyunluk.', 249.90, null, 'adet', false, 6277),
  -- tek-kullanimlik-piknik (16 yeni urun)
  ('tek-kullanimlik-piknik', 'Solo Karton Tabak', 'solo-karton-tabak-26-cm-20li', 'Solo', '20''li', 'Sağlam yapılı, 26 cm çapında karton tabak.', 69.90, null, 'paket', false, 6278),
  ('tek-kullanimlik-piknik', 'Roll-up Çatal Kaşık Bıçak Seti', 'rollup-catal-kasik-bicak-seti-18li', 'Roll-up', '18''li', 'Piknik ve davetler için hazır sofra takım seti.', 44.90, null, 'paket', false, 6279),
  ('tek-kullanimlik-piknik', 'Cimplast Buzdolabı Poşeti Jumbo', 'cimplast-buzdolabi-poseti-jumbo-50li', 'Cimplast', '50''li', 'Gıda saklamak için büyük boy buzdolabı poşeti.', 44.90, null, 'paket', false, 6280),
  ('tek-kullanimlik-piknik', 'Koroplast Dondurucu Torbası Kilitli', 'koroplast-dondurucu-torbasi-kilitli-20li', 'Koroplast', '20''li', 'Donmuş gıdalar için kilitli, kalın dondurucu torbası.', 49.90, null, 'paket', false, 6281),
  ('tek-kullanimlik-piknik', 'Alfem Fırın Kağıdı', 'alfem-firin-kagidi-20-m', 'Alfem', '20 m', 'Yapışmaz yüzeyli, fırınlık yemekler için pişirme kağıdı.', 44.90, null, 'adet', false, 6282),
  ('tek-kullanimlik-piknik', 'Comfort Çöp Poşeti Mutfak', 'comfort-cop-poseti-mutfak-40li', 'Comfort', '40''lı', 'Yırtılmaya dayanıklı, mutfak boy çöp poşeti.', 69.90, null, 'paket', false, 6283),
  ('tek-kullanimlik-piknik', 'Termos Çanta Katlanır', 'termos-canta-katlanir-15-l', '', '15 L', 'Piknik ve yolculuk için katlanabilir soğutucu çanta.', 179.90, null, 'adet', false, 6284),
  ('tek-kullanimlik-piknik', 'Plastik Limonluk Sıkma Aparatı', 'plastik-limonluk-sikma-aparati-2li', '', '2''li', 'Limon ve narenciye sıkmayı kolaylaştıran aparat.', 29.90, null, 'paket', false, 6285),
  ('tek-kullanimlik-piknik', 'Buz Kalıbı Poşeti Tek Kullanımlık', 'buz-kalibi-poseti-tek-kullanimlik-2li', '', '2''li', 'Kolay dökülen, tek kullanımlık buz kalıbı poşeti.', 24.90, null, 'paket', false, 6286),
  ('tek-kullanimlik-piknik', 'Piknik Battaniyesi Su Geçirmez', 'piknik-battaniyesi-su-gecirmez-200x150-cm', '', '200x150 cm', 'Alt yüzeyi su geçirmez, katlanabilir piknik battaniyesi.', 249.90, null, 'adet', false, 6287),
  ('tek-kullanimlik-piknik', 'Plastik Tuzluk Biberlik Seti', 'plastik-tuzluk-biberlik-seti-2li', '', '2''li', 'Piknik sofrası için pratik tuzluk biberlik ikilisi.', 19.90, null, 'paket', false, 6288),
  ('tek-kullanimlik-piknik', 'Karton Yemek Kutusu Kapaklı', 'karton-yemek-kutusu-kapakli-500-ml-10lu', '', '10''lu', 'Yemek paketleme için kapaklı karton kutu.', 54.90, null, 'paket', false, 6289),
  ('tek-kullanimlik-piknik', 'Plastik Şişe Suluk Soğutuculu', 'plastik-sise-suluk-sogutuculu-500-ml', '', '500 ml', 'İçindeki jel ile içeceği soğuk tutan suluk.', 69.90, null, 'adet', false, 6290),
  ('tek-kullanimlik-piknik', 'Piknik Sofra Örtüsü Kareli', 'piknik-sofra-ortusu-kareli-140x140-cm', '', '140x140 cm', 'Klasik kareli desenli, silinebilir sofra örtüsü.', 59.90, null, 'adet', false, 6291),
  ('tek-kullanimlik-piknik', 'Bardak Altlığı Karton', 'bardak-altligi-karton-50li', '', '50''li', 'Masaları koruyan, emici karton bardak altlığı.', 24.90, null, 'paket', false, 6292),
  ('tek-kullanimlik-piknik', 'Plastik Tepsi Servis Büyük Boy', 'plastik-tepsi-servis-buyuk-boy-3lu', '', '3''lü', 'Piknik ve davetler için dayanıklı servis tepsisi.', 49.90, null, 'paket', false, 6293),
  -- bebek (18 yeni urun)
  ('bebek', 'Aptamil Pronutra 1 Başlangıç Sütü', 'aptamil-pronutra-1-baslangic-sutu-400-g', 'Aptamil', '400 g', '0-6 ay bebekler için özel formüllü başlangıç sütü.', 349.90, null, 'adet', false, 6294),
  ('bebek', 'Bebelac Comfort Bebek Sütü', 'bebelac-comfort-bebek-sutu-400-g', 'Bebelac', '400 g', 'Sindirimi kolaylaştıran, hassas mideler için mama.', 339.90, null, 'adet', false, 6295),
  ('bebek', 'Hipp Organik 2 Devam Sütü', 'hipp-organik-2-devam-sutu-800-g', 'Hipp', '800 g', 'Organik tarım sertifikalı, 6 ay üzeri devam sütü.', 449.90, null, 'adet', true, 6296),
  ('bebek', 'Nestle NAN Optipro 1', 'nestle-nan-optipro-1-400-g', 'Nestle', '400 g', 'Protein yapısı anne sütüne yakın, başlangıç sütü.', 359.90, null, 'adet', false, 6297),
  ('bebek', 'Hero Baby Kavanoz Mama Ispanaklı', 'hero-baby-kavanoz-mama-ispanakli-200-g', 'Hero Baby', '200 g', 'Ek gıda döneminde, ıspanaklı kavanoz mama.', 44.90, null, 'adet', false, 6298),
  ('bebek', 'Milupa Meyveli Kaşık Mama', 'milupa-meyveli-kasik-mama-190-g', 'Milupa', '190 g', 'Karışık meyveli, kaşıkla verilen bebek maması.', 39.90, null, 'adet', false, 6299),
  ('bebek', 'Prima Aktif Bebek Bezi 5 Numara', 'prima-aktif-bebek-bezi-5-numara-36li', 'Prima', '36''lı', 'Nefes alabilen, geniş bel bantlı 5 numara bez.', 349.90, null, 'paket', false, 6300),
  ('bebek', 'Molfix Külot Bez 6 Numara', 'molfix-kulot-bez-6-numara-30lu', 'Molfix', '30''lu', 'Kolay giydirilen, yürüyen çocuklar için külot bez.', 289.90, null, 'paket', false, 6301),
  ('bebek', 'Sleepy Gold Bebek Bezi 3 Numara', 'sleepy-gold-bebek-bezi-3-numara-60li', 'Sleepy', '60''lı', 'Ekstra ince, yüksek emicilikli premium bebek bezi.', 259.90, null, 'paket', false, 6302),
  ('bebek', 'Canbebe Bebek Bezi 3 Numara', 'canbebe-bebek-bezi-3-numara-68li', 'Canbebe', '68''li', 'Yumuşak dokulu, sızdırmaz bariyerli bebek bezi.', 269.90, null, 'paket', false, 6303),
  ('bebek', 'Prima Islak Havlu Aloe Vera', 'prima-islak-havlu-aloe-vera-6li', 'Prima', '6''lı', 'Aloe vera özlü, hassas cilde uygun ıslak havlu.', 149.90, null, 'paket', false, 6304),
  ('bebek', 'Johnson''s Bebek Yağı Aloe Vera', 'johnsons-bebek-yagi-aloe-vera-300-ml', 'Johnson''s', '300 ml', 'Cildi yumuşatan, aloe vera içerikli bebek yağı.', 99.90, null, 'adet', false, 6305),
  ('bebek', 'Sudocrem Care & Protect', 'sudocrem-care-protect-125-g', 'Sudocrem', '125 g', 'Pişikleri önleyen, koruyucu bariyer kremi.', 179.90, null, 'adet', false, 6306),
  ('bebek', 'Chicco Diş Kaşıyıcı Halka', 'chicco-dis-kasiyici-halka-adet', 'Chicco', '1 adet', 'Diş çıkarma döneminde damakları rahatlatan halka.', 69.90, null, 'adet', false, 6307),
  ('bebek', 'Avent Emzik Silikon 6-18 Ay', 'avent-emzik-silikon-6-18-ay-2li', 'Avent', '2''li', 'Ortodontik formda, yumuşak silikon emzik ikilisi.', 129.90, null, 'paket', false, 6308),
  ('bebek', 'NUK Biberon Anti-Kolik', 'nuk-biberon-anti-kolik-260-ml', 'NUK', '260 ml', 'Hava yutmayı azaltan, anti-kolik sistemli biberon.', 179.90, null, 'adet', false, 6309),
  ('bebek', 'Bebek Mama Sandalyesi Taşınabilir', 'bebek-mama-sandalyesi-tasinabilir-adet', '', '1 adet', 'Katlanabilir, masaya takılan taşınabilir mama sandalyesi.', 899.90, null, 'adet', false, 6310),
  ('bebek', 'Bebek Tırnak Makası Yuvarlak Uçlu', 'bebek-tirnak-makasi-yuvarlak-uclu-adet', '', '1 adet', 'Güvenli yuvarlak uçlu, bebekler için tırnak makası.', 59.90, null, 'adet', false, 6311),
  -- evcil-hayvan (18 yeni urun)
  ('evcil-hayvan', 'Royal Canin Persian Yetişkin Kedi Maması', 'royal-canin-persian-yetiskin-kedi-mamasi-2-kg', 'Royal Canin', '2 kg', 'İran kedilerine özel, tüy yumağı önleyici formül.', 549.90, null, 'adet', false, 6312),
  ('evcil-hayvan', 'Purina Pro Plan Yavru Köpek Maması', 'purina-pro-plan-yavru-kopek-mamasi-3-kg', 'Purina Pro Plan', '3 kg', 'Yavru köpeklerin gelişimini destekleyen kuru mama.', 449.90, null, 'adet', false, 6313),
  ('evcil-hayvan', 'Bonacibo Kedi Maması Somonlu', 'bonacibo-kedi-mamasi-somonlu-1-5-kg', 'Bonacibo', '1,5 kg', 'Somonlu, yetişkin kediler için tam beslenme mamsı.', 289.90, null, 'adet', false, 6314),
  ('evcil-hayvan', 'Brit Care Köpek Maması Kuzulu', 'brit-care-kopek-mamasi-kuzulu-3-kg', 'Brit Care', '3 kg', 'Tahılsız formüllü, kuzu etli premium köpek maması.', 599.90, null, 'adet', false, 6315),
  ('evcil-hayvan', 'Purina Felix Jöle Karışık', 'purina-felix-jole-karisik-12li', 'Felix', '12''li', 'Jöle içinde et parçacıklı, yaş kedi maması paketi.', 189.90, null, 'paket', false, 6316),
  ('evcil-hayvan', 'Whiskas Kitten Yaş Mama Tavuklu', 'whiskas-kitten-yas-mama-tavuklu-85-g', 'Whiskas', '85 g', 'Yavru kediler için tavuklu, pouch yaş mama.', 19.90, null, 'adet', false, 6317),
  ('evcil-hayvan', 'Pedigree Puppy Kuru Mama', 'pedigree-puppy-kuru-mama-3-kg', 'Pedigree', '3 kg', 'Yavru köpekler için besin değeri dengeli kuru mama.', 349.90, null, 'adet', false, 6318),
  ('evcil-hayvan', 'Catsan Ultra Topaklaşan Kedi Kumu', 'catsan-ultra-topaklasan-kedi-kumu-5-l', 'Catsan', '5 L', 'Kokuyu anında hapseden, hızlı topaklaşan kedi kumu.', 249.90, null, 'adet', false, 6319),
  ('evcil-hayvan', 'Cat''s Best Öko Plus Kedi Kumu', 'cats-best-oko-plus-kedi-kumu-10-l', 'Cat''s Best', '10 L', 'Doğal odun bazlı, çevre dostu topaklaşan kedi kumu.', 349.90, null, 'adet', false, 6320),
  ('evcil-hayvan', 'Kedi Tuvalet Kum Küreği Plastik', 'kedi-tuvalet-kum-kuregi-plastik-adet', '', '1 adet', 'Delikli yüzeyli, kedi kumu temizleme küreği.', 49.90, null, 'adet', false, 6321),
  ('evcil-hayvan', 'Köpek Ödül Bisküvisi Tavuklu', 'kopek-odul-biskuvisi-tavuklu-500-g', '', '500 g', 'Eğitim ve ödüllendirme için tavuklu köpek bisküvisi.', 89.90, null, 'adet', false, 6322),
  ('evcil-hayvan', 'Kedi Otu Taze Saksı', 'kedi-otu-taze-saksi-adet', '', '1 adet', 'Kedilerin severek kokladığı, saksıda taze kedi otu.', 59.90, null, 'adet', false, 6323),
  ('evcil-hayvan', 'Köpek Yatağı Yıkanabilir Orta Boy', 'kopek-yatagi-yikanabilir-orta-boy-adet', '', '1 adet', 'Yumuşak dolgulu, makinede yıkanabilir köpek yatağı.', 449.90, null, 'adet', false, 6324),
  ('evcil-hayvan', 'Kedi Tırmalama Direği Peluş', 'kedi-tirmalama-diregi-pelus-adet', '', '1 adet', 'Peluş kaplı, sehpalı kedi tırmalama direği.', 599.90, null, 'adet', false, 6325),
  ('evcil-hayvan', 'Akvaryum Su Şartlandırıcı', 'akvaryum-su-sartlandirici-250-ml', '', '250 ml', 'Musluk suyundaki klor ve ağır metalleri nötralize eder.', 89.90, null, 'adet', false, 6326),
  ('evcil-hayvan', 'Kuş Kafesi Oyuncak Salıncak', 'kus-kafesi-oyuncak-salincak-adet', '', '1 adet', 'Muhabbet kuşları için renkli salıncak oyuncağı.', 69.90, null, 'adet', false, 6327),
  ('evcil-hayvan', 'Köpek Ağız Maskesi Ayarlanabilir M', 'kopek-agiz-maskesi-ayarlanabilir-m-adet', '', '1 adet', 'Ayarlanabilir kayışlı, orta boy köpek ağız maskesi.', 99.90, null, 'adet', false, 6328),
  ('evcil-hayvan', 'Kedi Taşıma Çantası Fileli', 'kedi-tasima-cantasi-fileli-adet', '', '1 adet', 'Havalandırma delikli, veteriner yolculukları için taşıma çantası.', 449.90, null, 'adet', false, 6329),
  -- ev-yasam (18 yeni urun)
  ('ev-yasam', 'Zwilling Şef Bıçağı', 'zwilling-sef-bicagi-20-cm', 'Zwilling', '20 cm', 'Almanya yapımı, paslanmaz çelik profesyonel şef bıçağı.', 899.90, null, 'adet', true, 6330),
  ('ev-yasam', 'Karaca Tost Makinesi', 'karaca-tost-makinesi-cift-tarafli', 'Karaca', '1 adet', 'Çift taraflı pişiren, yapışmaz plakalı tost makinesi.', 649.90, null, 'adet', false, 6331),
  ('ev-yasam', 'Fakir Su Isıtıcı', 'fakir-su-isitici-1-7-l', 'Fakir', '1,7 L', 'Hızlı kaynatan, otomatik kapanan paslanmaz su ısıtıcı.', 449.90, null, 'adet', false, 6332),
  ('ev-yasam', 'Tefal Blender Karıştırıcı Set', 'tefal-blender-karistirici-set', 'Tefal', '1 adet', 'Smoothie ve çorbalar için güçlü motorlu blender seti.', 999.90, null, 'adet', true, 6333),
  ('ev-yasam', 'Emsan Salata Küveti Cam', 'emsan-salata-kuveti-cam-adet', 'Emsan', '1 adet', 'Sofrada servis edilen, dayanıklı cam salata küveti.', 129.90, null, 'adet', false, 6334),
  ('ev-yasam', 'Paşabahçe Kahve Fincanı', 'pasabahce-kahve-fincani-6li', 'Paşabahçe', '6''lı', 'Espresso ve filtre kahve için zarif cam fincan seti.', 149.90, null, 'paket', false, 6335),
  ('ev-yasam', 'LAV Meşrubat Sürahisi', 'lav-mesrubat-surahisi-1-5-l', 'LAV', '1,5 L', 'Sofrada su ve meşrubat servisi için kapaklı sürahi.', 159.90, null, 'adet', false, 6336),
  ('ev-yasam', 'Beko Ütü Buharlı', 'beko-utu-buharli-2400w', 'Beko', '1 adet', 'Güçlü buhar püskürtmeli, seramik tabanlı ütü.', 899.90, null, 'adet', false, 6337),
  ('ev-yasam', 'Vestel Saç Kurutma Makinesi', 'vestel-sac-kurutma-makinesi-2000w', 'Vestel', '1 adet', 'İyonik teknolojili, hızlı kurutan saç kurutma makinesi.', 549.90, null, 'adet', false, 6338),
  ('ev-yasam', 'Philips Ampul E14 6W Sarı Işık', 'philips-ampul-e14-6w-sari-isik', 'Philips', '6 W', 'Avize ve lambalar için ince duylu LED ampul.', 49.90, null, 'adet', false, 6339),
  ('ev-yasam', 'Osram Sensörlü Gece Lambası', 'osram-sensorlu-gece-lambasi', 'Osram', '1 adet', 'Işık algıladığında otomatik yanan, prize takılan lamba.', 199.90, null, 'adet', false, 6340),
  ('ev-yasam', 'Plastik Saklama Kutusu Şeffaf', 'plastik-saklama-kutusu-seffaf-10-l', '', '10 L', 'Tekerlekli, dolap altına uygun şeffaf saklama kutusu.', 149.90, null, 'adet', false, 6341),
  ('ev-yasam', 'Vakumlu Saklama Poşeti Seti', 'vakumlu-saklama-poseti-seti-5li', '', '5''li', 'Havasını alarak gıdayı daha uzun süre koruyan poşet.', 129.90, null, 'paket', false, 6342),
  ('ev-yasam', 'Havlu Seti Banyo', 'havlu-seti-banyo-2li', '', '2''li', 'Yumuşak dokulu, yüksek emicilikte banyo havlu seti.', 249.90, null, 'paket', false, 6343),
  ('ev-yasam', 'Çamaşır Sepeti Katlanır', 'camasir-sepeti-katlanir-45-l', '', '45 L', 'Yer kaplamayan, katlanabilir file çamaşır sepeti.', 179.90, null, 'adet', false, 6344),
  ('ev-yasam', 'Paspas Seti Kova Sıkmalı', 'paspas-seti-kova-sikmali', '', '1 adet', 'Elle temas etmeden sıkma özellikli, tekerlekli paspas seti.', 599.90, null, 'adet', false, 6345),
  ('ev-yasam', 'Ütü Masası Katlanır', 'utu-masasi-katlanir', '', '1 adet', 'Ayarlanabilir yükseklikte, kolay katlanan ütü masası.', 799.90, null, 'adet', false, 6346),
  ('ev-yasam', 'Mutfak Önlüğü Su Geçirmez', 'mutfak-onlugu-su-gecirmez', '', '1 adet', 'Lekeye karşı koruyan, ayarlanabilir mutfak önlüğü.', 89.90, null, 'adet', false, 6347),
  -- mangal-komur (10 yeni urun)
  ('mangal-komur', 'Weber Briket Kömür', 'weber-briket-komur-4-5-kg', 'Weber', '4,5 kg', 'Uzun süre sabit ısı veren, kaliteli briket kömür.', 349.90, null, 'adet', false, 6348),
  ('mangal-komur', 'Coco Fire Hindistan Cevizi Briketi', 'coco-fire-hindistan-cevizi-briketi-3-kg', 'Coco Fire', '3 kg', 'Dumansız yanan, uzun ömürlü hindistan cevizi briketi.', 249.90, null, 'adet', false, 6349),
  ('mangal-komur', 'Meşe Odun Kırığı Tütsüleme', 'mese-odun-kirigi-tutsuleme-1-kg', '', '1 kg', 'Ete duman aroması katan, meşe odun kırığı.', 79.90, null, 'adet', false, 6350),
  ('mangal-komur', 'Mangal Ateşleme Tableti', 'mangal-atesleme-tableti-24lu', '', '24''lü', 'Kolay tutuşan, kokusuz mangal ateşleme tableti.', 59.90, null, 'paket', false, 6351),
  ('mangal-komur', 'Paslanmaz Mangal Şişi Kılıçlı', 'paslanmaz-mangal-sisi-kilicli-4lu', '', '4''lü', 'Geniş kılıçlı, et ve sebze için paslanmaz şiş.', 149.90, null, 'paket', false, 6352),
  ('mangal-komur', 'Katlanır Kamp Ocaklığı Üçgen', 'katlanir-kamp-ocakligi-ucgen', '', '1 adet', 'Hafif ve taşınabilir, üçgen formda kamp ocaklığı.', 199.90, null, 'adet', false, 6353),
  ('mangal-komur', 'Mangal Termometre İbreli', 'mangal-termometre-ibreli', '', '1 adet', 'Fırın ve mangal için ibreli sıcaklık ölçer.', 129.90, null, 'adet', false, 6354),
  ('mangal-komur', 'Izgara Kapaklı Balık Sepeti', 'izgara-kapakli-balik-sepeti', '', '1 adet', 'Balığın dağılmasını önleyen, kapaklı ızgara sepeti.', 179.90, null, 'adet', false, 6355),
  ('mangal-komur', 'Mangal Örtüsü Su Geçirmez', 'mangal-ortusu-su-gecirmez-buyuk-boy', '', '1 adet', 'Mangalı toz ve yağmurdan koruyan büyük boy örtü.', 249.90, null, 'adet', false, 6356),
  ('mangal-komur', 'Mangal Kömürü Torbası Meşe', 'mangal-komuru-torbasi-mese-8-kg', '', '8 kg', 'Uzun yanma süreli, ailelik boy meşe mangal kömürü.', 289.90, null, 'adet', false, 6357),
  -- cakmak-kibrit-tup (10 yeni urun)
  ('cakmak-kibrit-tup', 'Aygaz Tüp 12 kg Dolumu', 'aygaz-tup-12-kg-dolumu', 'Aygaz', '12 kg', 'Ev tipi ocaklar için dolu 12 kg LPG tüp.', 1249.90, null, 'adet', false, 6358),
  ('cakmak-kibrit-tup', 'İpragaz Tüp 12 kg Dolumu', 'ipragaz-tup-12-kg-dolumu', 'İpragaz', '12 kg', 'Mutfak kullanımına uygun, dolu 12 kg LPG tüp.', 1229.90, null, 'adet', false, 6359),
  ('cakmak-kibrit-tup', 'Milangaz Piknik Tüpü', 'milangaz-piknik-tupu-190-g', 'Milangaz', '190 g', 'Kamp ocakları için vidalı küçük gaz tüpü.', 89.90, null, 'adet', false, 6360),
  ('cakmak-kibrit-tup', 'Bic Slim Çakmak', 'bic-slim-cakmak-3lu', 'Bic', '3''lü', 'İnce gövdeli, cepte taşınabilir çakmak paketi.', 69.90, null, 'paket', false, 6361),
  ('cakmak-kibrit-tup', 'Cricket Elektronik Çakmak', 'cricket-elektronik-cakmak-2li', 'Cricket', '2''li', 'Piezo ateşlemeli, rüzgara dayanıklı çakmak.', 79.90, null, 'paket', false, 6362),
  ('cakmak-kibrit-tup', 'Şömine Kibriti Kutulu Uzun', 'somine-kibriti-kutulu-uzun-50li', '', '50''li', 'Şömine ve mangal için uzun çöplü kibrit.', 44.90, null, 'paket', false, 6363),
  ('cakmak-kibrit-tup', 'Kamp Tüpü Adaptörü Vidalı', 'kamp-tupu-adaptoru-vidali', '', '1 adet', 'Farklı tüp tiplerini kamp ocağına uyarlayan adaptör.', 79.90, null, 'adet', false, 6364),
  ('cakmak-kibrit-tup', 'Tüp Emniyet Vanası', 'tup-emniyet-vanasi', '', '1 adet', 'Gaz kaçağını önleyen, tüplere takılan emniyet vanası.', 149.90, null, 'adet', false, 6365),
  ('cakmak-kibrit-tup', 'Çakmak Gazı Dolum Seti Büyük', 'cakmak-gazi-dolum-seti-buyuk-400-ml', '', '400 ml', 'Çakmakları doldurmak için büyük boy gaz seti.', 59.90, null, 'adet', false, 6366),
  ('cakmak-kibrit-tup', 'Ocak Üstü Kıvılcım Ateşleyici Pilli', 'ocak-ustu-kivilcim-atesleyici-pilli', '', '1 adet', 'Pille çalışan, ocaklar için kıvılcım ateşleyici.', 99.90, null, 'adet', false, 6367),
  -- sarj-aleti-pil (16 yeni urun)
  ('sarj-aleti-pil', 'Samsung 25W Hızlı Şarj Adaptörü', 'samsung-25w-hizli-sarj-adaptoru', 'Samsung', '1 adet', 'USB-C çıkışlı, hızlı şarj destekli orijinal adaptör.', 349.90, null, 'adet', false, 6368),
  ('sarj-aleti-pil', 'Apple 20W USB-C Güç Adaptörü', 'apple-20w-usb-c-guc-adaptoru', 'Apple', '1 adet', 'iPhone ve iPad için orijinal hızlı şarj adaptörü.', 599.90, null, 'adet', true, 6369),
  ('sarj-aleti-pil', 'Baseus 65W GaN Çoklu Şarj Aleti', 'baseus-65w-gan-coklu-sarj-aleti', 'Baseus', '1 adet', 'Üç çıkışlı, laptop ve telefonları birlikte şarj eder.', 799.90, null, 'adet', false, 6370),
  ('sarj-aleti-pil', 'Anker PowerCore 10000 mAh Powerbank', 'anker-powercore-10000-mah-powerbank', 'Anker', '1 adet', 'Kompakt boyutlu, hızlı şarj destekli taşınabilir batarya.', 899.90, null, 'adet', true, 6371),
  ('sarj-aleti-pil', 'Xiaomi Kablosuz Şarj Pedi', 'xiaomi-kablosuz-sarj-pedi-20w', 'Xiaomi', '1 adet', 'Kablosuz şarj destekli telefonlar için hızlı şarj pedi.', 449.90, null, 'adet', false, 6372),
  ('sarj-aleti-pil', 'Duracell Şarj Edilebilir Pil AAA', 'duracell-sarj-edilebilir-pil-aaa-4lu-850mah', 'Duracell', '4''lü', 'Yüzlerce kez tekrar şarj edilebilen ince kalem pil.', 249.90, null, 'paket', false, 6373),
  ('sarj-aleti-pil', 'Varta Longlife Kalem Pil AA', 'varta-longlife-kalem-pil-aa-10lu', 'Varta', '10''lu', 'Uzun ömürlü, ekonomik boy alkalin kalem pil.', 99.90, null, 'paket', false, 6374),
  ('sarj-aleti-pil', 'Energizer Ultimate Lityum AA Pil', 'energizer-ultimate-lityum-aa-pil-4lu', 'Energizer', '4''lü', 'Aşırı düşük sıcaklıklarda bile çalışan lityum pil.', 189.90, null, 'paket', false, 6375),
  ('sarj-aleti-pil', 'Panasonic Düğme Pil LR44', 'panasonic-dugme-pil-lr44-6li', 'Panasonic', '6''lı', 'Saat ve küçük cihazlar için düğme pil paketi.', 59.90, null, 'paket', false, 6376),
  ('sarj-aleti-pil', 'USB-C to HDMI Adaptör Kablosu', 'usb-c-to-hdmi-adaptor-kablosu-2-m', '', '2 m', 'Telefonu televizyona bağlayan görüntü aktarım kablosu.', 249.90, null, 'adet', false, 6377),
  ('sarj-aleti-pil', 'Kablosuz Kulaklık Şarj Kutusu Yedek', 'kablosuz-kulaklik-sarj-kutusu-yedek', '', '1 adet', 'Kaybolan kulaklık kutuları için yedek şarj kutusu.', 349.90, null, 'adet', false, 6378),
  ('sarj-aleti-pil', 'Araç İçi Çift USB-C Hızlı Şarj Soketi', 'arac-ici-cift-usb-c-hizli-sarj-soketi', '', '1 adet', 'Çakmaklığa takılan, çift portlu hızlı araç şarj cihazı.', 179.90, null, 'adet', false, 6379),
  ('sarj-aleti-pil', 'Manyetik Kablosuz Şarj Standı', 'manyetik-kablosuz-sarj-standi-magsafe-uyumlu', '', '1 adet', 'Telefonu dik tutan, mıknatıslı kablosuz şarj standı.', 449.90, null, 'adet', false, 6380),
  ('sarj-aleti-pil', 'Powerbank Güneş Enerjili', 'powerbank-gunes-enerjili-20000-mah', '', '1 adet', 'Güneş paneliyle şarj olabilen, kamp için powerbank.', 799.90, null, 'adet', false, 6381),
  ('sarj-aleti-pil', 'USB Hub 7 Port Alüminyum', 'usb-hub-7-port-aluminyum', '', '1 adet', 'Bilgisayara birden fazla cihaz bağlamak için hub.', 349.90, null, 'adet', false, 6382),
  ('sarj-aleti-pil', 'Şarj Kablosu Örgülü Type-C', 'sarj-kablosu-orgulu-type-c-3-m', '', '3 m', 'Dayanıklı naylon örgülü, uzun boy şarj kablosu.', 99.90, null, 'adet', false, 6383),
  -- plaj-mayo-terlik (16 yeni urun)
  ('plaj-mayo-terlik', 'Kadın Straplez Mayo', 'kadin-straplez-mayo', '', '1 adet', 'Askısız, silikonlu bantla sabitlenen kadın mayosu.', 279.90, null, 'adet', false, 6384),
  ('plaj-mayo-terlik', 'Kadın Balconet Bikini Takım', 'kadin-balconet-bikini-takim', '', '1 adet', 'Destekli üst parçalı, şık desenli bikini takımı.', 299.90, null, 'adet', false, 6385),
  ('plaj-mayo-terlik', 'Erkek Aile Tipi Deniz Şortu Büyük Beden', 'erkek-aile-tipi-deniz-sortu-buyuk-beden', '', '1 adet', 'Rahat kesimli, büyük beden erkek deniz şortu.', 189.90, null, 'adet', false, 6386),
  ('plaj-mayo-terlik', 'Çocuk Karakter Baskılı Mayo', 'cocuk-karakter-baskili-mayo', '', '1 adet', 'Sevimli karakter baskılı, hızlı kuruyan çocuk mayosu.', 159.90, null, 'adet', false, 6387),
  ('plaj-mayo-terlik', 'Kadın Uzun Kollu Sporcu Mayosu UV Korumalı', 'kadin-uzun-kollu-sporcu-mayosu-uv-korumali', '', '1 adet', 'Güneşten koruyan, uzun kollu sporcu mayosu.', 349.90, null, 'adet', false, 6388),
  ('plaj-mayo-terlik', 'Erkek Terlik Ortopedik Taban', 'erkek-terlik-ortopedik-taban', '', '1 adet', 'Ayak sağlığını destekleyen, ortopedik tabanlı terlik.', 199.90, null, 'adet', false, 6389),
  ('plaj-mayo-terlik', 'Kadın Dolgu Tabanlı Deniz Terliği', 'kadin-dolgu-tabanli-deniz-terligi', '', '1 adet', 'Yumuşak dolgulu, rahat kadın deniz terliği.', 219.90, null, 'adet', false, 6390),
  ('plaj-mayo-terlik', 'Çocuk Işıklı Terlik', 'cocuk-isikli-terlik', '', '1 adet', 'Basıldıkça ışık yayan, eğlenceli çocuk terliği.', 149.90, null, 'adet', false, 6391),
  ('plaj-mayo-terlik', 'Yetişkin Yüzücü Gözlüğü Numaralı', 'yetiskin-yuzucu-gozlugu-numarali', '', '1 adet', 'Görme kusuruna göre numaralı yüzücü gözlüğü.', 249.90, null, 'adet', false, 6392),
  ('plaj-mayo-terlik', 'Çocuk Kolluk ve Simit Kirpi Desenli', 'cocuk-kolluk-simit-kirpi-desenli', '', '1 adet', 'Şişme kolluk ve simidi bir arada sunan set.', 129.90, null, 'paket', false, 6393),
  ('plaj-mayo-terlik', 'Mikrofiber Hızlı Kuruyan Plaj Havlusu XL', 'mikrofiber-hizli-kuruyan-plaj-havlusu-xl', '', '1 adet', 'Hafif, çabuk kuruyan büyük boy plaj havlusu.', 249.90, null, 'adet', false, 6394),
  ('plaj-mayo-terlik', 'Kadın Plaj Elbisesi Uzun', 'kadin-plaj-elbisesi-uzun', '', '1 adet', 'Hafif kumaştan, mayo üstü giyilen uzun plaj elbisesi.', 349.90, null, 'adet', false, 6395),
  ('plaj-mayo-terlik', 'Plaj Şezlongu Katlanır Alüminyum', 'plaj-sezlongu-katlanir-aluminyum', '', '1 adet', 'Hafif alüminyum iskeletli, katlanabilir plaj şezlongu.', 899.90, null, 'adet', false, 6396),
  ('plaj-mayo-terlik', 'Su Geçirmez Sırt Çantası', 'su-gecirmez-sirt-cantasi-20-l', '', '20 L', 'Tekne ve plaj için su geçirmez sırt çantası.', 449.90, null, 'adet', false, 6397),
  ('plaj-mayo-terlik', 'Çocuk Deniz Yeleği Yüzme Can Yeleği', 'cocuk-deniz-yelegi-yuzme-can-yelegi', '', '1 adet', 'Yüzmeyi öğrenen çocuklar için can yeleği.', 349.90, null, 'adet', false, 6398),
  ('plaj-mayo-terlik', 'Plaj Sepeti Katlanır File', 'plaj-sepeti-katlanir-file', '', '1 adet', 'Kum dökülmesini önleyen file dokulu plaj sepeti.', 179.90, null, 'adet', false, 6399),
  -- gunes-kremi-plaj (16 yeni urun)
  ('gunes-kremi-plaj', 'La Roche-Posay Anthelios Çocuk Spreyi SPF50', 'la-roche-posay-anthelios-cocuk-spreyi-spf50-200-ml', 'La Roche-Posay', '200 ml', 'Hassas çocuk cildi için çok yüksek korumalı sprey.', 449.90, null, 'adet', false, 6400),
  ('gunes-kremi-plaj', 'Avène Solaire Emülsiyon SPF50', 'avene-solaire-emulsiyon-spf50-50-ml', 'Avène', '50 ml', 'Hassas ciltler için termal su içeren güneş kremi.', 349.90, null, 'adet', false, 6401),
  ('gunes-kremi-plaj', 'Eucerin Oil Control Dry Touch SPF30', 'eucerin-oil-control-dry-touch-spf30-50-ml', 'Eucerin', '50 ml', 'Yağlı ciltler için mat bitişli güneş koruyucu.', 379.90, null, 'adet', false, 6402),
  ('gunes-kremi-plaj', 'Vichy Ideal Soleil Sprey SPF50', 'vichy-ideal-soleil-sprey-spf50-200-ml', 'Vichy', '200 ml', 'Hızlı emilen, yüksek korumalı vücut güneş spreyi.', 399.90, null, 'adet', true, 6403),
  ('gunes-kremi-plaj', 'Bioderma Photoderm Kids SPF50', 'bioderma-photoderm-kids-spf50-200-ml', 'Bioderma', '200 ml', 'Çocuklara özel, su ve tere dayanıklı güneş kremi.', 429.90, null, 'adet', false, 6404),
  ('gunes-kremi-plaj', 'Garnier Ambre Solaire Yağ Spreyi SPF6', 'garnier-ambre-solaire-yag-spreyi-spf6-150-ml', 'Garnier', '150 ml', 'Hızlı bronzlaşma için düşük korumalı yağ sprey.', 249.90, null, 'adet', false, 6405),
  ('gunes-kremi-plaj', 'Isdin Fotoprotector Fusion Fluid SPF50', 'isdin-fotoprotector-fusion-fluid-spf50-50-ml', 'Isdin', '50 ml', 'Yağsız dokulu, yüz için çok yüksek koruma.', 449.90, null, 'adet', false, 6406),
  ('gunes-kremi-plaj', 'Hawaiian Tropic After Sun Losyon', 'hawaiian-tropic-after-sun-losyon-200-ml', 'Hawaiian Tropic', '200 ml', 'Tropik kokulu, güneş sonrası nemlendirici losyon.', 249.90, null, 'adet', false, 6407),
  ('gunes-kremi-plaj', 'Carroten Aile Boy Güneş Sütü SPF30', 'carroten-aile-boy-gunes-sutu-spf30-300-ml', 'Carroten', '300 ml', 'Ekonomik ailelik boy, orta korumalı güneş sütü.', 299.90, null, 'adet', false, 6408),
  ('gunes-kremi-plaj', 'Sundance Roll-On Güneş Kremi SPF50', 'sundance-roll-on-gunes-kremi-spf50-50-ml', 'Sundance', '50 ml', 'Elleri kirletmeden uygulanan, roll-on güneş kremi.', 149.90, null, 'adet', false, 6409),
  ('gunes-kremi-plaj', 'Bioblas Güneş Sonrası Sprey', 'bioblas-gunes-sonrasi-sprey-200-ml', 'Bioblas', '200 ml', 'Serinletici, cildi yatıştıran güneş sonrası sprey.', 129.90, null, 'adet', false, 6410),
  ('gunes-kremi-plaj', 'Piz Buin Tan & Protect Yağ SPF15', 'piz-buin-tan-protect-yag-spf15-150-ml', 'Piz Buin', '150 ml', 'Bronzlaşmayı hızlandıran, koruyucu güneş yağı.', 349.90, null, 'adet', false, 6411),
  ('gunes-kremi-plaj', 'Plaj Şemsiyesi Katlanır Çanta ile', 'plaj-semsiyesi-katlanir-canta-200-cm', '', '200 cm', 'Taşıma çantalı, rüzgara dayanıklı plaj şemsiyesi.', 349.90, null, 'adet', false, 6412),
  ('gunes-kremi-plaj', 'Güneş Gözlüğü Aynalı UV400', 'gunes-gozlugu-aynali-uv400', '', '1 adet', 'UV400 korumalı, aynalı camlı güneş gözlüğü.', 129.90, null, 'adet', false, 6413),
  ('gunes-kremi-plaj', 'Yüz Güneş Bandı SPF50 Yapışkanlı', 'yuz-gunes-bandi-spf50-yapiskanli', '', '1 adet', 'Burun ve elmacık kemiğine yapıştırılan koruyucu bant.', 89.90, null, 'adet', false, 6414),
  ('gunes-kremi-plaj', 'Serinletici Boyun Havlusu Güneş Koruma', 'serinletici-boyun-havlusu-gunes-koruma', '', '1 adet', 'Islatıldığında serinleten, boyun için güneş koruma havlusu.', 99.90, null, 'adet', false, 6415),
  -- sisme-bot-havuz (10 yeni urun)
  ('sisme-bot-havuz', 'Intex Ejderha Binek Şişme', 'intex-ejderha-binek-sisme', 'Intex', '1 adet', 'Havuz eğlencesi için büyük boy ejderha binek.', 349.90, null, 'adet', false, 6416),
  ('sisme-bot-havuz', 'Bestway Aile Boy Şişme Havuz', 'bestway-aile-boy-sisme-havuz-305x183-cm', 'Bestway', '305x183 cm', 'Bahçe kullanımı için geniş aile boy şişme havuz.', 899.90, null, 'adet', true, 6417),
  ('sisme-bot-havuz', 'Intex Su Topu Işıklı', 'intex-su-topu-isikli', 'Intex', '1 adet', 'Suda parlayan, gece oyunları için ışıklı top.', 129.90, null, 'adet', false, 6418),
  ('sisme-bot-havuz', 'Bestway Şişme Kürek', 'bestway-sisme-kurek-2li', 'Bestway', '2''li', 'Şişme botlar için hafif plastik kürek ikilisi.', 149.90, null, 'paket', false, 6419),
  ('sisme-bot-havuz', 'Havuz Yer Halısı Yumuşak Zemin', 'havuz-yer-halisi-yumusak-zemin-4lu', '', '4''lü', 'Havuz altına serilen, birleşebilir yumuşak zemin parçası.', 249.90, null, 'paket', false, 6420),
  ('sisme-bot-havuz', 'Havuz pH Test Kiti', 'havuz-ph-test-kiti', '', '1 adet', 'Havuz suyunun pH dengesini ölçen test kiti.', 99.90, null, 'adet', false, 6421),
  ('sisme-bot-havuz', 'Şişme Yüzük Simit Flamingo', 'sisme-yuzuk-simit-flamingo-90-cm', '', '90 cm', 'Flamingo desenli, renkli şişme deniz simidi.', 199.90, null, 'adet', false, 6422),
  ('sisme-bot-havuz', 'Elektrikli Şişirme Pompası Taşınabilir', 'elektrikli-sisirme-pompasi-tasinabilir-12v', '', '1 adet', 'Araç çakmaklığından çalışan, hızlı şişirme pompası.', 349.90, null, 'adet', false, 6423),
  ('sisme-bot-havuz', 'Havuz Merdiveni Katlanır', 'havuz-merdiveni-katlanir-3-basamak', '', '1 adet', 'Havuza güvenli giriş için üç basamaklı merdiven.', 449.90, null, 'adet', false, 6424),
  ('sisme-bot-havuz', 'Şişme Havuz Yaması Su Altı Tipi', 'sisme-havuz-yamasi-su-alti-tipi-5li', '', '5''li', 'Su içinde bile yapıştırılabilen onarım yaması.', 44.90, null, 'paket', false, 6425),
  -- sinek-bocek-kovucu (16 yeni urun)
  ('sinek-bocek-kovucu', 'Baygon Doğa Bitkisel Sivrisinek Spreyi', 'baygon-doga-bitkisel-sivrisinek-spreyi-200-ml', 'Baygon', '200 ml', 'Bitkisel içerikli, doğal formüllü sivrisinek spreyi.', 129.90, null, 'adet', false, 6426),
  ('sinek-bocek-kovucu', 'Raid Karınca ve Hamamböceği Toz İlacı', 'raid-karinca-hamambocegi-toz-ilaci-250-g', 'Raid', '250 g', 'Uzun etkili, serpme formunda böcek ilacı.', 89.90, null, 'adet', false, 6427),
  ('sinek-bocek-kovucu', 'Off Botanicals Doğal Sivrisinek Kovucu Sprey', 'off-botanicals-dogal-sivrisinek-kovucu-sprey-100-ml', 'Off', '100 ml', 'Bitkisel yağ bazlı, doğal içerikli kovucu sprey.', 119.90, null, 'adet', false, 6428),
  ('sinek-bocek-kovucu', 'Vape Mat Elektrikli Yedek Sıvı', 'vape-mat-elektrikli-yedek-sivi-3lu', 'Vape', '3''lü', 'Elektrikli cihazlar için yedek sivrisinek sıvısı.', 99.90, null, 'paket', false, 6429),
  ('sinek-bocek-kovucu', 'Baygon Güve Kovucu Askı Lavanta', 'baygon-guve-kovucu-aski-lavanta-5li', 'Baygon', '5''li', 'Dolaplara asılan, lavanta kokulu güve kovucu.', 54.90, null, 'paket', false, 6430),
  ('sinek-bocek-kovucu', 'Elektrikli Sinek Tuzağı UV Lambalı Duvar Tipi', 'elektrikli-sinek-tuzagi-uv-lambali-duvar-tipi', '', '1 adet', 'Duvara monte edilen, UV ışıklı sinek tuzağı.', 449.90, null, 'adet', false, 6431),
  ('sinek-bocek-kovucu', 'Kapı Önü Fırça Sineklik Manyetik', 'kapi-onu-firca-sineklik-manyetik', '', '1 adet', 'Kapı eşiğine takılan, fırça tipi sineklik bariyeri.', 129.90, null, 'adet', false, 6432),
  ('sinek-bocek-kovucu', 'Bahçe Tipi Sivrisinek Kovucu Mum Sitronella', 'bahce-tipi-sivrisinek-kovucu-mum-sitronella', '', '1 adet', 'Açık alanlarda kullanılan, sitronella kokulu bahçe mumu.', 89.90, null, 'adet', false, 6433),
  ('sinek-bocek-kovucu', 'Karınca İlacı Sıvı Konsantre', 'karinca-ilaci-sivi-konsantre-250-ml', '', '250 ml', 'Sulandırılıp uygulanan, güçlü karınca ilacı.', 99.90, null, 'adet', false, 6434),
  ('sinek-bocek-kovucu', 'Güve Kovucu Naftalin Tablet', 'guve-kovucu-naftalin-tablet-10lu', '', '10''lu', 'Klasik formüllü, dolap içi güve kovucu tablet.', 34.90, null, 'paket', false, 6435),
  ('sinek-bocek-kovucu', 'Sivrisinek Kovucu Bebek Bantı Yamalı', 'sivrisinek-kovucu-bebek-banti-yamali-24lu', '', '24''lü', 'Kıyafete yapıştırılan, bebekler için doğal kovucu bant.', 64.90, null, 'paket', false, 6436),
  ('sinek-bocek-kovucu', 'Güneş Enerjili Bahçe Böcek Kovucu Cihaz', 'gunes-enerjili-bahce-bocek-kovucu-cihaz', '', '1 adet', 'Solar panelle çalışan, ultrasonik bahçe böcek kovucu.', 349.90, null, 'adet', false, 6437),
  ('sinek-bocek-kovucu', 'Güve Kovucu Sedir Ahşap Küp', 'guve-kovucu-sedir-ahsap-kup-4lu', '', '4''lü', 'Doğal sedir ağacından, kokulu güve kovucu küp.', 79.90, null, 'paket', false, 6438),
  ('sinek-bocek-kovucu', 'Sinek Yapışkan Bant Tavan Tipi', 'sinek-yapiskan-bant-tavan-tipi-10lu', '', '10''lu', 'Tavandan asılan, güçlü yapışkanlı sinek bandı.', 49.90, null, 'paket', false, 6439),
  ('sinek-bocek-kovucu', 'Kene Kovucu Sprey Köpek ve Kedi İçin', 'kene-kovucu-sprey-kopek-kedi-icin-100-ml', '', '100 ml', 'Evcil hayvanlarda pire ve kene oluşumunu önleyen sprey.', 149.90, null, 'adet', false, 6440),
  ('sinek-bocek-kovucu', 'Güve Kovucu Elektrikli Fişli Cihaz', 'guve-kovucu-elektrikli-fisli-cihaz', '', '1 adet', 'Prize takılan, dolap içi elektrikli güve kovucu.', 199.90, null, 'adet', false, 6441)
on conflict (slug) do nothing;
