-- ============================================================
-- Yeni Mahalle Market: Getir seviyesinde katalog genisletmesi (A)
-- 4 kategoriye Getir tarzi gercekci yeni urunler ekler:
--   meyve-sebze(70), cips-kuruyemis(30), sut-kahvaltilik(50),
--   icecek-su(40) => toplam 190 urun.
--
-- Kolon sirasi mevcut seed ile BIREBIR AYNI:
--   (category_slug, name, slug, brand, size_text, description,
--    price, compare_at_price, unit, is_featured, sort)
-- compare_at_price HER ZAMAN null (indirim yok).
-- Sort degerleri 5000'den baslar, 5189'a kadar surekli artar
-- (mevcut degerlerle cakismaz).
-- Slug'lar mevcut seed'lerdeki urunlerle CAKISMAZ.
-- Idempotent: on conflict (slug) do nothing.
-- ============================================================

-- Meyve & Sebze (70 yeni urun: 35 meyve, 23 sebze, 12 yesillik)
insert into public.products (category_slug, name, slug, brand, size_text, description, price, compare_at_price, unit, is_featured, sort) values
  -- Meyve
  ('meyve-sebze', 'Aşı Nar', 'asi-nar-kg', '', '1 kg', 'Taneleri iri ve sulu, ekşi-tatlı aşı nar çeşidi.', 79.90, null, 'kg', false, 5000),
  ('meyve-sebze', 'Taze İncir', 'taze-incir-kg', '', '1 kg', 'Mis kokulu, yumuşak ve tatlı taze yaş incir.', 99.90, null, 'kg', false, 5001),
  ('meyve-sebze', 'Trabzon Hurması', 'trabzon-hurmasi-kg', '', '1 kg', 'Turuncu renkli, tatlı ve yumuşak dokulu Trabzon hurması.', 64.90, null, 'kg', false, 5002),
  ('meyve-sebze', 'Yaş Hurma', 'yas-hurma-kg', '', '1 kg', 'Enerji deposu, taze ve yumuşak yaş hurma.', 149.90, null, 'kg', false, 5003),
  ('meyve-sebze', 'Ananas', 'ananas-adet', '', 'adet', 'Tropikal aromalı, sulu ve tatlı taze ananas.', 89.90, null, 'adet', true, 5004),
  ('meyve-sebze', 'Mango', 'mango-adet', '', 'adet', 'Kremamsı dokulu, tatlı ve aromalı olgun mango.', 69.90, null, 'adet', false, 5005),
  ('meyve-sebze', 'Fuerte Avokado', 'avokado-fuerte-adet', '', 'adet', 'Yağlı ve kremamsı, salatalık Fuerte avokado.', 34.90, null, 'adet', false, 5006),
  ('meyve-sebze', 'Can Eriği', 'can-erigi-kg', '', '1 kg', 'Ekşi-tatlı, mor kabuklu mevsim can eriği.', 59.90, null, 'kg', false, 5007),
  ('meyve-sebze', 'Sarı Erik', 'sari-erik-kg', '', '1 kg', 'Sulu ve tatlımsı, sarı kabuklu erik çeşidi.', 54.90, null, 'kg', false, 5008),
  ('meyve-sebze', 'Yeşil Erik', 'yesil-erik-kg', '', '1 kg', 'Ekşimsi ve çıtır, tuzla yenen taze yeşil erik.', 39.90, null, 'kg', false, 5009),
  ('meyve-sebze', 'Kiraz', 'kiraz-kg', '', '1 kg', 'İri taneli, sulu ve tatlı mevsim 0900 Ziraat kirazı.', 149.90, null, 'kg', true, 5010),
  ('meyve-sebze', 'Vişne', 'visne-kg', '', '1 kg', 'Ekşi aromalı, reçellik ve komposto vişnesi.', 69.90, null, 'kg', false, 5011),
  ('meyve-sebze', 'Böğürtlen', 'bogurtlen-125-g', '', '125 g', 'Antioksidan deposu, tatlı-ekşi taze böğürtlen.', 79.90, null, 'paket', false, 5012),
  ('meyve-sebze', 'Yaban Mersini', 'yaban-mersini-125-g', '', '125 g', 'Vitamin deposu, taze ve tatlı yaban mersini.', 89.90, null, 'paket', false, 5013),
  ('meyve-sebze', 'Ahududu', 'ahududu-125-g', '', '125 g', 'Kokulu ve tatlı-ekşi, taze ahududu (frambuaz).', 84.90, null, 'paket', false, 5014),
  ('meyve-sebze', 'Ejder Meyvesi', 'ejder-meyvesi-adet', '', 'adet', 'Egzotik görünümlü, hafif tatlı ejder meyvesi (pitaya).', 99.90, null, 'adet', false, 5015),
  ('meyve-sebze', 'Passiflora', 'passiflora-adet', '', 'adet', 'Ekşi-tatlı aromalı, egzotik çarkıfelek meyvesi.', 44.90, null, 'adet', false, 5016),
  ('meyve-sebze', 'Pembe Greyfurt', 'pembe-greyfurt-kg', '', '1 kg', 'Tatlımsı ve sulu, pembe etli greyfurt çeşidi.', 44.90, null, 'kg', false, 5017),
  ('meyve-sebze', 'Klemantin Mandalina', 'klemantin-mandalina-kg', '', '1 kg', 'Çekirdeksiz ve kolay soyulan, tatlı klemantin mandalina.', 54.90, null, 'kg', false, 5018),
  ('meyve-sebze', 'Satsuma Mandalina', 'satsuma-mandalina-kg', '', '1 kg', 'Erken mevsim, tatlı ve gevşek kabuklu satsuma mandalina.', 49.90, null, 'kg', false, 5019),
  ('meyve-sebze', 'Washington Portakal', 'washington-portakal-kg', '', '1 kg', 'Göbekli ve çekirdeksiz, tatlı yemelik Washington portakal.', 39.90, null, 'kg', false, 5020),
  ('meyve-sebze', 'Kan Portakalı', 'kan-portakali-kg', '', '1 kg', 'Bordo renkli eti, ekşi-tatlı aromalı kan portakalı.', 49.90, null, 'kg', false, 5021),
  ('meyve-sebze', 'Sarı Kivi', 'sari-kivi-kg', '', '1 kg', 'Tüysüz kabuklu, tatlı ve sarı etli kivi çeşidi.', 79.90, null, 'kg', false, 5022),
  ('meyve-sebze', 'Kırmızı Üzüm', 'kirmizi-uzum-kg', '', '1 kg', 'Taneli ve tatlı, çekirdekli kırmızı sofralık üzüm.', 64.90, null, 'kg', false, 5023),
  ('meyve-sebze', 'Çekirdekli Kara Üzüm', 'kara-uzum-cekirdekli-kg', '', '1 kg', 'Koyu renkli, aromalı ve tatlı kara üzüm.', 69.90, null, 'kg', false, 5024),
  ('meyve-sebze', 'Razaki Üzüm', 'razaki-uzum-kg', '', '1 kg', 'İri taneli, gevrek ve tatlı Razaki üzümü.', 74.90, null, 'kg', true, 5025),
  ('meyve-sebze', 'Galia Kavunu', 'galia-kavunu-kg', '', '1 kg', 'Ballı ve kokulu, yeşil etli Galia kavunu.', 39.90, null, 'kg', false, 5026),
  ('meyve-sebze', 'Ananas Kavunu', 'ananas-kavunu-kg', '', '1 kg', 'Ananas aromalı, tatlı ve sulu yaz kavunu.', 44.90, null, 'kg', false, 5027),
  ('meyve-sebze', 'Çekirdeksiz Karpuz', 'cekirdeksiz-karpuz-kg', '', '1 kg', 'Çekirdeksiz ve sulu, kolay yenilir tatlı karpuz.', 24.90, null, 'kg', false, 5028),
  ('meyve-sebze', 'Sarı Karpuz', 'sari-karpuz-kg', '', '1 kg', 'Sarı etli, bal gibi tatlı mevsim karpuzu.', 27.90, null, 'kg', false, 5029),
  ('meyve-sebze', 'Yeşil Limon', 'yesil-limon-kg', '', '1 kg', 'Ekşi aromalı, kokteyl ve yemeklik yeşil limon (misket limonu).', 89.90, null, 'kg', false, 5030),
  ('meyve-sebze', 'Çağla', 'cagla-kg', '', '1 kg', 'Tuzla yenen, ekşimsi ve çıtır taze çağla (yeşil badem).', 74.90, null, 'kg', false, 5031),
  ('meyve-sebze', 'Kestane', 'kestane-kg', '', '1 kg', 'Kavrulmalık ve haşlamalık, taze kabuklu kestane.', 99.90, null, 'kg', false, 5032),
  ('meyve-sebze', 'Yeni Dünya', 'yeni-dunya-kg', '', '1 kg', 'Mayıs mevsiminin turuncu, tatlı-ekşi yeni dünya meyvesi.', 64.90, null, 'kg', false, 5033),
  ('meyve-sebze', 'Karadut', 'karadut-125-g', '', '125 g', 'Koyu mor renkli, tatlı ve aromalı taze karadut.', 59.90, null, 'paket', false, 5034),
  -- Sebze
  ('meyve-sebze', 'Enginar', 'enginar-adet', '', 'adet', 'Zeytinyağlı yemeklik, temizlenmemiş taze enginar.', 34.90, null, 'adet', false, 5035),
  ('meyve-sebze', 'Kırmızı Pancar', 'kirmizi-pancar-kg', '', '1 kg', 'Salatalık ve turşuluk, taze kök kırmızı pancar.', 27.90, null, 'kg', false, 5036),
  ('meyve-sebze', 'Haşlanmış Pancar', 'haslanmis-kirmizi-pancar-kg', '', '1 kg', 'Yıkanmış ve haşlanmış, salatalık hazır kırmızı pancar.', 44.90, null, 'kg', false, 5037),
  ('meyve-sebze', 'Beyaz Turp', 'beyaz-turp-kg', '', '1 kg', 'Çıtır ve hafif acımsı, salatalık beyaz turp.', 29.90, null, 'kg', false, 5038),
  ('meyve-sebze', 'Barbunya Fasulye', 'barbunya-fasulye-kg', '', '1 kg', 'Zeytinyağlılık, benekli taze barbunya fasulyesi.', 59.90, null, 'kg', false, 5039),
  ('meyve-sebze', 'Çalı Fasulyesi', 'cali-fasulyesi-kg', '', '1 kg', 'İnce ve gevrek, zeytinyağlılık çalı fasulyesi.', 69.90, null, 'kg', false, 5040),
  ('meyve-sebze', 'Sarı Kabak', 'sari-kabak-kg', '', '1 kg', 'Yemeklik ve kızartmalık, sarı kabuklu taze kabak.', 34.90, null, 'kg', false, 5041),
  ('meyve-sebze', 'Mini Patlıcan', 'mini-patlican-kg', '', '1 kg', 'Dolmalık ve turşuluk, küçük boy mini patlıcan.', 54.90, null, 'kg', false, 5042),
  ('meyve-sebze', 'Kırmızı Dolmalık Biber', 'kirmizi-dolmalik-biber-kg', '', '1 kg', 'Tatlı ve etli, iç doldurmaya uygun kırmızı dolmalık biber.', 64.90, null, 'kg', false, 5043),
  ('meyve-sebze', 'Sarı Dolmalık Biber', 'sari-dolmalik-biber-kg', '', '1 kg', 'Tatlı ve etli, renkli salatalık sarı dolmalık biber.', 64.90, null, 'kg', false, 5044),
  ('meyve-sebze', 'Pembe Domates', 'pembe-domates-kg', '', '1 kg', 'Az çekirdekli, etli ve tatlı pembe domates.', 44.90, null, 'kg', true, 5045),
  ('meyve-sebze', 'Kabak Çiçeği', 'kabak-cicegi-demet', '', 'demet', 'Dolmalık, taze kesilmiş kabak çiçeği demeti.', 39.90, null, 'adet', false, 5046),
  ('meyve-sebze', 'Taze Bakla', 'taze-bakla-kg', '', '1 kg', 'Zeytinyağlılık, körpe ve taze bakla.', 49.90, null, 'kg', false, 5047),
  ('meyve-sebze', 'Ayıklanmış Bezelye', 'ayiklanmis-bezelye-250-g', '', '250 g', 'Kabuğu ayıklanmış, pişirmeye hazır taze bezelye.', 44.90, null, 'paket', false, 5048),
  ('meyve-sebze', 'Kuşkonmaz', 'kuskonmaz-demet', '', 'demet', 'Izgaralık ve sotelik, taze yeşil kuşkonmaz demeti.', 89.90, null, 'adet', false, 5049),
  ('meyve-sebze', 'Kök Şalgam', 'kok-salgam-kg', '', '1 kg', 'Turşuluk ve yemeklik, taze kök şalgam.', 24.90, null, 'kg', false, 5050),
  ('meyve-sebze', 'Brüksel Lahanası', 'bruksel-lahanasi-250-g', '', '250 g', 'Fırınlık ve sotelik, minyatür Brüksel lahanası.', 49.90, null, 'paket', false, 5051),
  ('meyve-sebze', 'Dilimli Bal Kabağı', 'dilimli-balkabagi-kg', '', '1 kg', 'Doğranmış ve temizlenmiş, tatlılık dilimli bal kabağı.', 34.90, null, 'kg', false, 5052),
  ('meyve-sebze', 'Kabak Julyen', 'kabak-julyen-300-g', '', '300 g', 'İnce şeritler halinde doğranmış, pişirmeye hazır kabak.', 39.90, null, 'paket', false, 5053),
  ('meyve-sebze', 'Sote Sebze Karışımı', 'sote-sebze-karisimi-500-g', '', '500 g', 'Havuç, kabak ve biberden hazır doğranmış sote karışımı.', 54.90, null, 'paket', false, 5054),
  ('meyve-sebze', 'Çorbalık Sebze Karışımı', 'corbalik-sebze-karisimi-500-g', '', '500 g', 'Havuç, kereviz ve soğandan hazır doğranmış çorbalık karışım.', 49.90, null, 'paket', false, 5055),
  ('meyve-sebze', 'Doğranmış Soğan', 'dogranmis-sogan-200-g', '', '200 g', 'Yemeklere hazır, temizlenmiş doğranmış soğan.', 24.90, null, 'paket', false, 5056),
  ('meyve-sebze', 'Taze Sarımsak', 'taze-sarimsak-baglama', '', 'bağ', 'Yeşil gövdeli, hafif aromalı taze yaş sarımsak.', 29.90, null, 'adet', false, 5057),
  -- Yesillik
  ('meyve-sebze', 'Tere', 'tere-baglama', '', 'bağ', 'Salata ve sandviçlik, mineral deposu taze tere.', 12.90, null, 'adet', false, 5058),
  ('meyve-sebze', 'Semizotu', 'semizotu-baglama', '', 'bağ', 'Yoğurtlu salatalık, etli yapraklı taze semizotu.', 19.90, null, 'adet', false, 5059),
  ('meyve-sebze', 'Pazı', 'pazi-baglama', '', 'bağ', 'Zeytinyağlılık ve sotelik, geniş yapraklı taze pazı.', 17.90, null, 'adet', false, 5060),
  ('meyve-sebze', 'Fesleğen', 'feslegen-baglama', '', 'bağ', 'Salata ve mezelere aroma katan taze fesleğen.', 14.90, null, 'adet', false, 5061),
  ('meyve-sebze', 'Kişniş', 'kisnis-baglama', '', 'bağ', 'Baharatlı yemeklere tazelik katan taze kişniş.', 14.90, null, 'adet', false, 5062),
  ('meyve-sebze', 'Aysberg Marul', 'aysberg-marul-adet', '', 'adet', 'Çıtır ve sulu, sandviçlik aysberg marul.', 27.90, null, 'adet', false, 5063),
  ('meyve-sebze', 'Kırmızı Kıvırcık Marul', 'kirmizi-kivircik-marul-adet', '', 'adet', 'Bordo yapraklı, salatalık kırmızı kıvırcık marul.', 26.90, null, 'adet', false, 5064),
  ('meyve-sebze', 'Lolo Rosso Marul', 'lolo-rosso-marul-adet', '', 'adet', 'Kıvrık kenarlı, dekoratif kırmızı lolo rosso marul.', 27.90, null, 'adet', false, 5065),
  ('meyve-sebze', 'Göbek Salata', 'gobek-salata-adet', '', 'adet', 'Sıkı ve çıtır yapraklı, salatalık göbek salata.', 29.90, null, 'adet', false, 5066),
  ('meyve-sebze', 'Kereviz Sapı', 'kereviz-sapi-baglama', '', 'bağ', 'Çorbalık ve sotelik, çıtır yeşil kereviz sapı.', 34.90, null, 'adet', false, 5067),
  ('meyve-sebze', 'Frenk Soğanı', 'frenk-sogani-baglama', '', 'bağ', 'İnce yapraklı, hafif soğan aromalı frenk soğanı.', 16.90, null, 'adet', false, 5068),
  ('meyve-sebze', 'Taze Kekik', 'taze-kekik-baglama', '', 'bağ', 'Salata ve etlere aroma katan taze kekik.', 14.90, null, 'adet', false, 5069)
on conflict (slug) do nothing;

-- Cips & Kuruyemis (30 yeni urun: 9 kuru meyve, 21 kuruyemis)
insert into public.products (category_slug, name, slug, brand, size_text, description, price, compare_at_price, unit, is_featured, sort) values
  ('cips-kuruyemis', 'Kuru Dut 100 g', 'kuru-dut-100-g', 'Tadım', '100 g', 'Doğal kurutulmuş, tatlı ve lifli beyaz kuru dut.', 74.90, null, 'paket', false, 5070),
  ('cips-kuruyemis', 'Kuru Erik 200 g', 'kuru-erik-200-g', 'Tadım', '200 g', 'Çekirdekli, ekşimsi-tatlı kurutulmuş erik.', 94.90, null, 'paket', false, 5071),
  ('cips-kuruyemis', 'Kuru Muz 150 g', 'kuru-muz-150-g', 'Tadım', '150 g', 'Cipsi andıran, tatlı ve çıtır kurutulmuş muz dilimi.', 84.90, null, 'paket', false, 5072),
  ('cips-kuruyemis', 'Kuru Kızılcık 150 g', 'kuru-kizilcik-150-g', 'Tadım', '150 g', 'Ekşimsi-tatlı, antioksidan deposu kurutulmuş kızılcık.', 89.90, null, 'paket', false, 5073),
  ('cips-kuruyemis', 'Kuru Ananas 150 g', 'kuru-ananas-150-g', 'Tadım', '150 g', 'Tropikal aromalı, çıtır kurutulmuş ananas dilimi.', 94.90, null, 'paket', true, 5074),
  ('cips-kuruyemis', 'Tropik Meyve Karışımı 200 g', 'tropik-meyve-karisimi-200-g', 'Tadım', '200 g', 'Mango, ananas ve papaya karışımlı kurutulmuş tropik meyve.', 119.90, null, 'paket', false, 5075),
  ('cips-kuruyemis', 'Kuru Elma 150 g', 'kuru-elma-150-g', 'Tadım', '150 g', 'İnce dilimli, doğal ve tatlı kurutulmuş elma.', 79.90, null, 'paket', false, 5076),
  ('cips-kuruyemis', 'Goji Berry 100 g', 'goji-berry-100-g', 'Tadım', '100 g', 'Süper besin, antioksidan deposu kurutulmuş goji berry.', 149.90, null, 'paket', false, 5077),
  ('cips-kuruyemis', 'Kuru Vişne 150 g', 'kuru-visne-150-g', 'Tadım', '150 g', 'Ekşi-tatlı aromalı, kurutulmuş çekirdeksiz vişne.', 99.90, null, 'paket', false, 5078),
  ('cips-kuruyemis', 'Çam Fıstığı 50 g', 'cam-fistigi-50-g', '', '50 g', 'Pilav ve tatlılara katılan, kremamsı iç çam fıstığı.', 149.90, null, 'paket', true, 5079),
  ('cips-kuruyemis', 'Kabuklu Ceviz 500 g', 'kabuklu-ceviz-500-g', '', '500 g', 'Kırmalık, açık kabuklu taze kabuklu ceviz.', 179.90, null, 'paket', false, 5080),
  ('cips-kuruyemis', 'Çiğ Fındık İçi 150 g', 'cig-findik-ici-150-g', 'Tadım', '150 g', 'Kavrulmamış, doğal ve sağlıklı çiğ iç fındık.', 139.90, null, 'paket', false, 5081),
  ('cips-kuruyemis', 'Tuzsuz Antep Fıstığı İçi 150 g', 'tuzsuz-antep-fistigi-ici-150-g', 'Tadım', '150 g', 'Tuz eklenmemiş, doğal kavrulmuş Antep fıstığı içi.', 199.90, null, 'paket', false, 5082),
  ('cips-kuruyemis', 'Makademya Fıstığı 100 g', 'makademya-fistigi-100-g', '', '100 g', 'Kremamsı dokulu, premium kavrulmuş makademya fıstığı.', 249.90, null, 'paket', false, 5083),
  ('cips-kuruyemis', 'Pekan Cevizi İçi 100 g', 'pekan-cevizi-ici-100-g', '', '100 g', 'Tatlımsı aromalı, çıtır pekan cevizi içi.', 179.90, null, 'paket', false, 5084),
  ('cips-kuruyemis', 'Brezilya Fıstığı 100 g', 'brezilya-fistigi-100-g', '', '100 g', 'İri taneli, yağlı ve besleyici Brezilya fıstığı.', 199.90, null, 'paket', false, 5085),
  ('cips-kuruyemis', 'Kavrulmuş Kestane 200 g', 'kavrulmus-kestane-200-g', '', '200 g', 'Kış atıştırmalığı, tuzlu kavrulmuş kestane.', 89.90, null, 'paket', false, 5086),
  ('cips-kuruyemis', 'Tuzsuz Ay Çekirdeği 200 g', 'tuzsuz-aycekirdegi-200-g', 'Tadım', '200 g', 'Tuz eklenmemiş, doğal kavrulmuş ay çekirdeği.', 49.90, null, 'paket', false, 5087),
  ('cips-kuruyemis', 'Kavrulmuş Kavun Çekirdeği 150 g', 'kavrulmus-kavun-cekirdegi-150-g', 'Peyman', '150 g', 'Tuzlu ve kavrulmuş, geleneksel kavun çekirdeği.', 59.90, null, 'paket', false, 5088),
  ('cips-kuruyemis', 'Kavrulmuş Karpuz Çekirdeği 150 g', 'kavrulmus-karpuz-cekirdegi-150-g', 'Peyman', '150 g', 'Tuzlu ve kavrulmuş, iri taneli karpuz çekirdeği.', 59.90, null, 'paket', false, 5089),
  ('cips-kuruyemis', 'Kabuklu Yer Fıstığı 300 g', 'kabuklu-yer-fistigi-300-g', '', '300 g', 'Kavrulmuş, kabuğuyla çıtlanan yer fıstığı.', 54.90, null, 'paket', false, 5090),
  ('cips-kuruyemis', 'Çikolatalı Leblebi 150 g', 'cikolatali-leblebi-150-g', 'Tadım', '150 g', 'Sütlü çikolata kaplı, çıtır sarı leblebi.', 79.90, null, 'paket', false, 5091),
  ('cips-kuruyemis', 'Ballı Kaju 150 g', 'balli-kaju-150-g', 'Tadım', '150 g', 'Bal kaplamalı, tatlı ve kremamsı kavrulmuş kaju.', 179.90, null, 'paket', false, 5092),
  ('cips-kuruyemis', 'Dilimli Badem 100 g', 'dilimli-badem-100-g', 'Tadım', '100 g', 'İnce dilimlenmiş, atıştırmalık ve pastacılık badem.', 99.90, null, 'paket', false, 5093),
  ('cips-kuruyemis', 'Kavrulmuş Fındık Tuzlu 150 g', 'kavrulmus-findik-tuzlu-150-g', 'Tadım', '150 g', 'Tuzlu ve kavrulmuş, çıtır iç fındık.', 139.90, null, 'paket', false, 5094),
  ('cips-kuruyemis', 'Kuruyemiş ve Kuru Meyve Karışımı 250 g', 'kuruyemis-kuru-meyve-karisimi-250-g', 'Tadım', '250 g', 'Fındık, kaju ve kuru kayısı karışımlı enerji dolu mix.', 129.90, null, 'paket', true, 5095),
  ('cips-kuruyemis', 'Tuzsuz Karışık Kuruyemiş 200 g', 'tuzsuz-karisik-kuruyemis-200-g', 'Tadım', '200 g', 'Tuz eklenmemiş, badem ve fındıklı doğal karışım.', 149.90, null, 'paket', false, 5096),
  ('cips-kuruyemis', 'Acı Baharatlı Yer Fıstığı 140 g', 'aci-baharatli-yer-fistigi-140-g', 'Peyman', '140 g', 'Acı baharatlı, kavrulmuş çıtır yer fıstığı.', 44.90, null, 'paket', false, 5097),
  ('cips-kuruyemis', 'Sarımsaklı Ay Çekirdeği 200 g', 'sarimsakli-aycekirdegi-200-g', 'Peyman', '200 g', 'Sarımsak aromalı, kavrulmuş ay çekirdeği.', 54.90, null, 'paket', false, 5098),
  ('cips-kuruyemis', 'Acı Leblebi 200 g', 'aci-leblebi-200-g', 'Tadım', '200 g', 'Baharatlı ve acı, kavrulmuş sarı leblebi.', 49.90, null, 'paket', false, 5099)
on conflict (slug) do nothing;

-- Sut & Kahvaltilik (50 yeni urun)
insert into public.products (category_slug, name, slug, brand, size_text, description, price, compare_at_price, unit, is_featured, sort) values
  ('sut-kahvaltilik', 'Laktozsuz Süt 1 L', 'pinar-laktozsuz-sut-1-l', 'Pınar', '1 L', 'Sindirimi kolay, laktoz hassasiyeti için tam yağlı laktozsuz süt.', 44.90, null, 'adet', false, 5100),
  ('sut-kahvaltilik', 'Laktozsuz Süt 1 L', 'sutas-laktozsuz-sut-1-l', 'Sütaş', '1 L', 'Doğal tatlı, sindirimi kolay laktozsuz UHT süt.', 46.90, null, 'adet', false, 5101),
  ('sut-kahvaltilik', 'Protein Süt 750 ml', 'sutas-protein-sut-750-ml', 'Sütaş', '750 ml', 'Yüksek proteinli, spor sonrası içimlik süt.', 59.90, null, 'adet', true, 5102),
  ('sut-kahvaltilik', 'Kefir Çilek 400 ml', 'tikvesli-kefir-cilek-400-ml', 'Tikveşli', '400 ml', 'Probiyotik kültürlü, çilek aromalı meyveli kefir.', 39.90, null, 'adet', false, 5103),
  ('sut-kahvaltilik', 'Kefir Karışık Meyve 400 ml', 'altinkilic-kefir-meyveli-400-ml', 'Altınkılıç', '400 ml', 'Bağırsak dostu, karışık meyve aromalı kefir.', 39.90, null, 'adet', false, 5104),
  ('sut-kahvaltilik', 'Kefir Light 1 L', 'icim-kefir-light-1-l', 'İçim', '1 L', 'Az yağlı, hafif ve ferahlatıcı sade kefir.', 54.90, null, 'adet', false, 5105),
  ('sut-kahvaltilik', 'Tam Yağlı Süt 1 L', 'eker-tam-yagli-sut-1-l', 'Eker', '1 L', 'Kahvaltılık ve tarifelere, günlük tam yağlı UHT süt.', 42.90, null, 'adet', false, 5106),
  ('sut-kahvaltilik', 'Yarım Yağlı Süt 1 L', 'yayla-yarim-yagli-sut-1-l', 'Yayla', '1 L', 'Hafif ve dengeli, günlük yarım yağlı UHT süt.', 39.90, null, 'adet', false, 5107),
  ('sut-kahvaltilik', 'Keçi Sütü 1 L', 'aynes-keci-sutu-1-l', 'Aynes', '1 L', 'Doğal ve besleyici, geleneksel keçi sütü.', 74.90, null, 'adet', false, 5108),
  ('sut-kahvaltilik', 'Manda Sütü 1 L', 'yorukoglu-manda-sutu-1-l', 'Yörükoğlu', '1 L', 'Yoğun kıvamlı, kaymak bağlayan manda sütü.', 89.90, null, 'adet', false, 5109),
  ('sut-kahvaltilik', 'Dil Peyniri 200 g', 'pinar-dil-peyniri-200-g', 'Pınar', '200 g', 'Lif lif açılan, tuzu dengeli klasik dil peyniri.', 79.90, null, 'adet', false, 5110),
  ('sut-kahvaltilik', 'Örgü Peyniri 250 g', 'muratbey-orgu-peyniri-250-g', 'Muratbey', '250 g', 'Geleneksel usul örülmüş, hafif tuzlu örgü peyniri.', 99.90, null, 'adet', false, 5111),
  ('sut-kahvaltilik', 'Hellim Peyniri 250 g', 'hellim-peyniri-250-g', '', '250 g', 'Izgaralık ve tavalık, tuzlu sert hellim peyniri.', 149.90, null, 'adet', true, 5112),
  ('sut-kahvaltilik', 'Mozzarella Peyniri 200 g', 'sutas-mozzarella-200-g', 'Sütaş', '200 g', 'Yumuşak ve elastik, pizzalık taze mozzarella.', 119.90, null, 'adet', false, 5113),
  ('sut-kahvaltilik', 'Rendelenmiş Mozzarella 180 g', 'pinar-mozzarella-rendelenmis-180-g', 'Pınar', '180 g', 'Kolay eriyen, pizza ve makarnalık rendelenmiş mozzarella.', 99.90, null, 'paket', false, 5114),
  ('sut-kahvaltilik', 'Ezine Peyniri Light 500 g', 'yorsan-ezine-light-500-g', 'Yorsan', '500 g', 'Az yağlı, hafif ve tuzu dengeli Ezine peyniri.', 219.90, null, 'adet', false, 5115),
  ('sut-kahvaltilik', 'Mihaliç Peyniri 400 g', 'mihalic-peyniri-400-g', '', '400 g', 'Bursa yöresi, koyun sütünden olgunlaştırılmış Mihaliç peyniri.', 169.90, null, 'adet', false, 5116),
  ('sut-kahvaltilik', 'Çerkez Peyniri 300 g', 'cerkez-peyniri-300-g', '', '300 g', 'Yumuşak dokulu, hafif tuzlu geleneksel Çerkez peyniri.', 189.90, null, 'adet', false, 5117),
  ('sut-kahvaltilik', 'Kars Gravyer Peyniri 300 g', 'kars-gravyer-peyniri-300-g', 'Kafkas', '300 g', 'Sert kıvamlı, yoğun aromalı Kars gravyer peyniri.', 259.90, null, 'adet', false, 5118),
  ('sut-kahvaltilik', 'Cheddar Peyniri Dilimli 200 g', 'sutas-cheddar-dilimli-200-g', 'Sütaş', '200 g', 'Hamburger ve sandviçlik, dilimli cheddar peyniri.', 139.90, null, 'paket', false, 5119),
  ('sut-kahvaltilik', 'Otlu Krem Peynir 300 g', 'pinar-krem-peynir-otlu-300-g', 'Pınar', '300 g', 'İnce otlu, sürülebilir kutu krem peynir.', 89.90, null, 'adet', false, 5120),
  ('sut-kahvaltilik', 'Sade Krem Peynir 300 g', 'pinar-krem-peynir-sade-300-g', 'Pınar', '300 g', 'Kremamsı ve yumuşak, sürülebilir sade krem peynir.', 84.90, null, 'adet', false, 5121),
  ('sut-kahvaltilik', 'Eritme Kaşar Dilimli 200 g', 'icim-eritme-kasar-dilimli-200-g', 'İçim', '200 g', 'Tost ve hamburgere hızla eriyen dilimli kaşar.', 89.90, null, 'paket', false, 5122),
  ('sut-kahvaltilik', 'Rendelenmiş Kaşar 200 g', 'muratbey-kasar-rendelenmis-200-g', 'Muratbey', '200 g', 'Makarna ve pizzalık, kolay eriyen rendelenmiş kaşar.', 99.90, null, 'paket', false, 5123),
  ('sut-kahvaltilik', 'Süzme Yoğurt Light 500 g', 'sutas-suzme-yogurt-light-500-g', 'Sütaş', '500 g', 'Az yağlı, kremamsı kıvamda light süzme yoğurt.', 64.90, null, 'adet', false, 5124),
  ('sut-kahvaltilik', 'Kaymaklı Yoğurt Cam Kavanoz 900 g', 'yorsan-kaymakli-yogurt-cam-900-g', 'Yorsan', '900 g', 'Cam kavanozda, üzeri kaymaklı geleneksel yoğurt.', 89.90, null, 'adet', false, 5125),
  ('sut-kahvaltilik', 'Meyveli Yoğurt Muz 4x100 g', 'danone-meyveli-yogurt-muz-4x100-g', 'Danone', '4x100 g', 'Çocukların sevdiği, muzlu kase yoğurt.', 49.90, null, 'paket', false, 5126),
  ('sut-kahvaltilik', 'Bal Cevizli Yoğurt 130 g', 'sutas-bal-cevizli-yogurt-130-g', 'Sütaş', '130 g', 'Bal ve ceviz katkılı, atıştırmalık kase yoğurt.', 34.90, null, 'adet', false, 5127),
  ('sut-kahvaltilik', 'Yunan Usulü Yoğurt 500 g', 'pinar-yunan-usulu-yogurt-500-g', 'Pınar', '500 g', 'Yoğun ve kremamsı, süzme kıvamlı Yunan usulü yoğurt.', 79.90, null, 'adet', true, 5128),
  ('sut-kahvaltilik', 'İçilebilir Probiyotik Yoğurt 200 ml', 'activia-icilebilir-yogurt-200-ml', 'Activia', '200 ml', 'Sindirim dostu, içilebilir probiyotik yoğurt.', 34.90, null, 'adet', false, 5129),
  ('sut-kahvaltilik', 'Keçi Yoğurdu 500 g', 'aynes-keci-yogurdu-500-g', 'Aynes', '500 g', 'Doğal ve yoğun kıvamlı, geleneksel keçi yoğurdu.', 99.90, null, 'adet', false, 5130),
  ('sut-kahvaltilik', 'Süzme Yoğurt Kova Light 1 kg', 'icim-light-suzme-yogurt-1-kg', 'İçim', '1 kg', 'Az yağlı, ailelik kova süzme yoğurt.', 99.90, null, 'adet', false, 5131),
  ('sut-kahvaltilik', 'Tuzlu Tereyağı 250 g', 'sutas-tuzlu-tereyagi-250-g', 'Sütaş', '250 g', 'Kahvaltılık, hafif tuzlu gerçek tereyağı.', 129.90, null, 'adet', false, 5132),
  ('sut-kahvaltilik', 'Sıvı Tereyağı 400 ml', 'icim-sivi-tereyagi-400-ml', 'İçim', '400 ml', 'Kızartma ve pişirmelik, pratik şişe sıvı tereyağı.', 149.90, null, 'adet', false, 5133),
  ('sut-kahvaltilik', 'Light Margarin 500 g', 'sana-light-margarin-500-g', 'Sana', '500 g', 'Az yağlı, kahvaltılık kıvamda light margarin.', 79.90, null, 'adet', false, 5134),
  ('sut-kahvaltilik', 'Ayçiçek Yağlı Margarin 1 kg', 'becel-margarin-1-kg', 'Becel', '1 kg', 'Bitkisel yağlardan, kalp dostu ayçiçek yağlı margarin.', 119.90, null, 'adet', false, 5135),
  ('sut-kahvaltilik', 'Kahvaltılık Tereyağı Tablet 10x10 g', 'pinar-tereyagi-tablet-10x10-g', 'Pınar', '10x10 g', 'Tek porsiyonluk, pratik kahvaltılık tereyağı tableti.', 64.90, null, 'paket', false, 5136),
  ('sut-kahvaltilik', 'Kestane Balı 460 g', 'balparmak-kestane-bali-460-g', 'Balparmak', '460 g', 'Koyu renkli, yoğun aromalı kestane balı.', 259.90, null, 'adet', true, 5137),
  ('sut-kahvaltilik', 'Çam Balı 460 g', 'altiparmak-cam-bali-460-g', 'Altıparmak', '460 g', 'Ege yöresi, koyu kıvamlı ve aromalı çam balı.', 349.90, null, 'adet', false, 5138),
  ('sut-kahvaltilik', 'Tahin Pekmez Karışımı 350 g', 'koska-tahin-pekmez-350-g', 'Koska', '350 g', 'Hazır karıştırılmış, kahvaltılık tahin pekmez karışımı.', 99.90, null, 'adet', false, 5139),
  ('sut-kahvaltilik', 'Gül Reçeli 350 g', 'oba-gul-receli-350-g', 'Oba', '350 g', 'Kokulu ve yoğun kıvamlı, geleneksel gül reçeli.', 89.90, null, 'adet', false, 5140),
  ('sut-kahvaltilik', 'İncir Reçeli 380 g', 'tamek-incir-receli-380-g', 'Tamek', '380 g', 'Parça incirli, tatlı ve yoğun kıvamlı reçel.', 74.90, null, 'adet', false, 5141),
  ('sut-kahvaltilik', 'Portakal Reçeli 380 g', 'tamek-portakal-receli-380-g', 'Tamek', '380 g', 'Kabuklu ve aromalı, ekşi-tatlı portakal reçeli.', 64.90, null, 'adet', false, 5142),
  ('sut-kahvaltilik', 'Ayva Reçeli 380 g', 'oba-ayva-receli-380-g', 'Oba', '380 g', 'Kokulu ve kırmızı renkli, geleneksel ayva reçeli.', 74.90, null, 'adet', false, 5143),
  ('sut-kahvaltilik', 'Yaban Mersini Reçeli 320 g', 'tamek-yaban-mersini-receli-320-g', 'Tamek', '320 g', 'Antioksidan deposu, yoğun meyveli yaban mersini reçeli.', 89.90, null, 'adet', false, 5144),
  ('sut-kahvaltilik', 'Keçiboynuzu Pekmezi 380 g', 'koska-keciboynuzu-pekmezi-380-g', 'Koska', '380 g', 'Doğal ve koyu kıvamlı, kahvaltılık keçiboynuzu pekmezi.', 84.90, null, 'adet', false, 5145),
  ('sut-kahvaltilik', 'Dut Pekmezi 380 g', 'koska-dut-pekmezi-380-g', 'Koska', '380 g', 'Demir deposu, koyu kıvamlı dut pekmezi.', 89.90, null, 'adet', false, 5146),
  ('sut-kahvaltilik', 'Susamlı Tahin 500 g', 'koska-tahin-susamli-500-g', 'Koska', '500 g', 'Kavrulmuş susamdan, saf ve kıvamlı tahin.', 139.90, null, 'adet', false, 5147),
  ('sut-kahvaltilik', 'Somonlu Krem Peynir 150 g', 'pinar-krem-peynir-somonlu-150-g', 'Pınar', '150 g', 'İnce somon parçacıklı, sürülebilir krem peynir.', 79.90, null, 'adet', false, 5148),
  ('sut-kahvaltilik', 'Laktozsuz Tereyağı 200 g', 'icim-laktozsuz-tereyagi-200-g', 'İçim', '200 g', 'Laktoz hassasiyeti için üretilmiş gerçek tereyağı.', 139.90, null, 'adet', false, 5149)
on conflict (slug) do nothing;

-- Icecek & Su (40 yeni urun)
insert into public.products (category_slug, name, slug, brand, size_text, description, price, compare_at_price, unit, is_featured, sort) values
  ('icecek-su', 'Kola Light 1 L', 'coca-cola-light-1-l', 'Coca-Cola', '1 L', 'Az kalorili, klasik kola tadında light içecek.', 36.90, null, 'adet', false, 5150),
  ('icecek-su', 'Kola Kiraz 330 ml', 'coca-cola-kiraz-330-ml', 'Coca-Cola', '330 ml', 'Kiraz aromalı, gazlı ve serinletici kola.', 29.90, null, 'adet', true, 5151),
  ('icecek-su', 'Fanta Limon 1 L', 'fanta-limon-1-l', 'Fanta', '1 L', 'Limon aromalı, ferahlatıcı gazlı içecek.', 34.90, null, 'adet', false, 5152),
  ('icecek-su', 'Pepsi Light 1 L', 'pepsi-light-1-l', 'Pepsi', '1 L', 'Az kalorili, klasik kola tadında light içecek.', 32.90, null, 'adet', false, 5153),
  ('icecek-su', 'Fanta Elma 1 L', 'fanta-elma-1-l', 'Fanta', '1 L', 'Elma aromalı, gazlı ve tatlı serinletici içecek.', 34.90, null, 'adet', false, 5154),
  ('icecek-su', 'Gazoz Limon 1 L', 'yedigun-limon-1-l', 'Yedigün', '1 L', 'Limon aromalı, hafif gazlı yerli gazoz.', 27.90, null, 'adet', false, 5155),
  ('icecek-su', 'Gazoz Vişne 250 ml', 'uludag-gazoz-visne-250-ml', 'Uludağ', '250 ml', 'Vişne aromalı, nostaljik lezzette gazoz.', 19.90, null, 'adet', false, 5156),
  ('icecek-su', 'Tonik Elma 1 L', 'schweppes-elma-1-l', 'Schweppes', '1 L', 'Elma aromalı, kokteyllik gazlı tonik.', 42.90, null, 'adet', false, 5157),
  ('icecek-su', 'Kola Zero 1 L', 'cola-turka-zero-1-l', 'Cola Turka', '1 L', 'Şekersiz, yerli üretim kola tadında gazlı içecek.', 29.90, null, 'adet', false, 5158),
  ('icecek-su', 'Gazoz Portakal 1 L', 'fruko-portakal-1-l', 'Fruko', '1 L', 'Portakal aromalı, bol gazlı nostaljik gazoz.', 29.90, null, 'adet', false, 5159),
  ('icecek-su', 'C Vitaminli İçecek Limon 200 ml', 'beypazari-c-vitamini-limon-200-ml', 'Beypazarı', '200 ml', 'C vitamini katkılı, limon aromalı ferahlatıcı içecek.', 16.90, null, 'adet', false, 5160),
  ('icecek-su', 'C Vitamini İçeceği 250 ml', 'dopigo-c-vitamini-250-ml', 'Dopigo', '250 ml', 'Günlük C vitamini ihtiyacına, meyveli fonksiyonel içecek.', 29.90, null, 'adet', false, 5161),
  ('icecek-su', 'Kombucha Elma Sirkeli 330 ml', 'kevita-kombucha-elma-330-ml', 'KeVita', '330 ml', 'Doğal fermente, elma sirkeli probiyotik kombucha.', 59.90, null, 'adet', true, 5162),
  ('icecek-su', 'Kombucha Zencefil Limon 330 ml', 'kombu-kombucha-zencefil-330-ml', 'Kombu Company', '330 ml', 'Zencefil ve limon aromalı, fermente kombucha çayı.', 59.90, null, 'adet', false, 5163),
  ('icecek-su', 'Buzlu Kahve Karamel 250 ml', 'nescafe-buzlu-kahve-karamel-250-ml', 'Nescafe', '250 ml', 'Soğuk servis, karamel aromalı hazır buzlu kahve.', 44.90, null, 'adet', false, 5164),
  ('icecek-su', 'Buzlu Kahve Mocha 250 ml', 'jacobs-buzlu-kahve-mocha-250-ml', 'Jacobs', '250 ml', 'Kakaolu ve kremamsı, hazır mocha buzlu kahve.', 44.90, null, 'adet', false, 5165),
  ('icecek-su', 'Soğuk Filtre Kahve 250 ml', 'kahve-dunyasi-soguk-filtre-250-ml', 'Kahve Dünyası', '250 ml', 'Soğuk demleme usulü, hazır şişe filtre kahve.', 54.90, null, 'adet', false, 5166),
  ('icecek-su', 'Buzlu Kahve Sade Şekersiz 250 ml', 'nescafe-buzlu-kahve-sade-250-ml', 'Nescafe', '250 ml', 'Şekersiz, sade aromalı hazır buzlu kahve.', 42.90, null, 'adet', false, 5167),
  ('icecek-su', 'Köpüklü Ayran 300 ml', 'sek-kopuklu-ayran-300-ml', 'Sek', '300 ml', 'Yayık usulü, bol köpüklü geleneksel ayran.', 19.90, null, 'adet', false, 5168),
  ('icecek-su', 'Ayran Şişe 250 ml', 'icim-ayran-sise-250-ml', 'İçim', '250 ml', 'Yanınızda taşınabilir, pratik şişe ayran.', 17.90, null, 'adet', false, 5169),
  ('icecek-su', 'Tuzsuz Ayran 1 L', 'pinar-tuzsuz-ayran-1-l', 'Pınar', '1 L', 'Tuz eklenmemiş, doğal ve hafif ayran.', 39.90, null, 'adet', false, 5170),
  ('icecek-su', 'Ayran Kutu 4x200 ml', 'sutas-ayran-kutu-4x200-ml', 'Sütaş', '4x200 ml', 'Çocuk beslenmesine pratik, pipetli kutu ayran.', 44.90, null, 'paket', false, 5171),
  ('icecek-su', 'Acı Şalgam Suyu 1 L', 'elvan-aci-salgam-1-l', 'Elvan', '1 L', 'Baharatlı ve ekşi, geleneksel acı şalgam suyu.', 39.90, null, 'adet', true, 5172),
  ('icecek-su', 'Tatlı Şalgam Suyu 1 L', 'elvan-tatli-salgam-1-l', 'Elvan', '1 L', 'Hafif baharatlı, tatlı-ekşi şalgam suyu.', 39.90, null, 'adet', false, 5173),
  ('icecek-su', 'Zencefilli Limonata 1 L', 'dimes-zencefilli-limonata-1-l', 'Dimes', '1 L', 'Zencefil aromalı, ekşi-tatlı ferahlatıcı limonata.', 39.90, null, 'adet', false, 5174),
  ('icecek-su', 'Karpuzlu Limonata 1 L', 'uludag-karpuzlu-limonata-1-l', 'Uludağ', '1 L', 'Yaz aroması, karpuz katkılı ferahlatıcı limonata.', 37.90, null, 'adet', false, 5175),
  ('icecek-su', 'Ev Usulü Limonata 330 ml', 'ev-usulu-limonata-330-ml', '', '330 ml', 'Taze sıkma tadında, şekeri dengeli ev usulü limonata.', 24.90, null, 'adet', false, 5176),
  ('icecek-su', 'Soğuk Çay Ananas 1 L', 'fuse-tea-ananas-1-l', 'Fuse Tea', '1 L', 'Tropikal ananas aromalı, buz gibi soğuk çay.', 39.90, null, 'adet', false, 5177),
  ('icecek-su', 'Soğuk Çay Böğürtlen 330 ml', 'lipton-ice-tea-bogurtlen-330-ml', 'Lipton', '330 ml', 'Böğürtlen aromalı, ferahlatıcı soğuk çay.', 19.90, null, 'adet', false, 5178),
  ('icecek-su', 'Beyaz Çay Soğuk 500 ml', 'dogadan-beyaz-cay-soguk-500-ml', 'Doğadan', '500 ml', 'Hafif aromalı, antioksidan deposu soğuk beyaz çay.', 34.90, null, 'adet', false, 5179),
  ('icecek-su', 'Ananas Suyu 1 L', 'cappy-ananas-1-l', 'Cappy', '1 L', 'Tropikal aromalı, tatlı ve sulu ananas suyu.', 44.90, null, 'adet', false, 5180),
  ('icecek-su', 'Mango Nektarı 1 L', 'tamek-mango-1-l', 'Tamek', '1 L', 'Kremamsı ve tatlı, tropikal mango nektarı.', 44.90, null, 'adet', false, 5181),
  ('icecek-su', 'Kayısı Nektarı 1 L', 'dimes-kayisi-1-l', 'Dimes', '1 L', 'Yoğun aromalı, tatlı Malatya kayısı nektarı.', 42.90, null, 'adet', false, 5182),
  ('icecek-su', 'Multivitamin Meyve Suyu 1 L', 'cappy-multivitamin-1-l', 'Cappy', '1 L', 'Çok meyveli, vitamin deposu karışık meyve suyu.', 46.90, null, 'adet', false, 5183),
  ('icecek-su', 'Greyfurt Suyu 1 L', 'dimes-greyfurt-1-l', 'Dimes', '1 L', 'Ekşimsi-tatlı, C vitamini deposu greyfurt suyu.', 42.90, null, 'adet', false, 5184),
  ('icecek-su', 'Damacana Su 12 L', 'erikli-damacana-12-l', 'Erikli', '12 L', 'Ev ve ofis için orta boy, doğal kaynak suyu damacana.', 69.90, null, 'adet', false, 5185),
  ('icecek-su', 'Pet Su 1,5 L', 'hayat-su-1-5-l', 'Hayat', '1,5 L', 'Günlük kullanım için orta boy pet şişe doğal su.', 19.90, null, 'adet', false, 5186),
  ('icecek-su', 'Pet Su 24x0,33 L', 'erikli-su-033-l-24lu', 'Erikli', '24x0,33 L', 'Ofis ve toplu tüketim için küçük boy su kolisi.', 89.90, null, 'paket', false, 5187),
  ('icecek-su', 'Maden Suyu Karpuz 6x200 ml', 'sirma-maden-suyu-karpuz-6li', 'Sırma', '6x200 ml', 'Karpuz aromalı, doğal mineralli maden suyu.', 44.90, null, 'paket', false, 5188),
  ('icecek-su', 'Maden Suyu Mandalina 6x200 ml', 'beypazari-maden-suyu-mandalina-6li', 'Beypazarı', '6x200 ml', 'Mandalina aromalı, ferahlatıcı doğal maden suyu.', 44.90, null, 'paket', false, 5189)
on conflict (slug) do nothing;
